#!/usr/bin/env python3
"""Generate abcd-isa/src/legacy_table.rs — the legacy (file format 0.0.0.2)
opcode translation table.

Inputs (regenerate from upstream history; see design doc in the emitted
file's header comment):

  1. OLD table: the OpenHarmony 3.1-era ISA, generated from
     arkcompiler_runtime_core@OpenHarmony-v3.1-Release isa/isa.yaml combined
     (isa/combine.rb) with the last pre-2022-08-18-refactoring ecma_isa.yaml
     (arkcompiler_js_runtime commit cb7bc0f08, 2023-02-14), dumped via the
     upstream isa/gen.rb + isa/isapi.rb with a `sig|prefix|idx|fmt|size|ops`
     ERB template. Byte-level verified: this exact table decodes all 105,995
     instructions of the 11 wild 0.0.0.2 packages with zero unknown bytes.
  2. VARIANTS: the generated bytecode.rs of abcd-isa-sys (build artifact),
     used to validate variant names and field types.

Usage:
  gen_legacy_table.py OLD_TABLE VARIANTS_RS OUTPUT_RS

The mapping itself is the curated MAPPING dict below: legacy opcode ->
modern Bytecode variant + operand token list. Operand tokens:
  "0"          synthesized Imm(0) — modern IC-slot immediate the legacy
               format does not carry
  "v0".."v3"   legacy register operand i -> Reg
  "imm"        legacy immediate -> Imm (sign-extended when the legacy
               operand type is signed)
  "id"         legacy id operand -> EntityId (raw value; for strings a
               32-bit file offset, for methods a 16-bit index)
  "jmp"        legacy jump immediate -> Label(0), raw offset returned for
               the caller's jump-resolution pass
"""

import re
import sys
from collections import defaultdict

# ---------------------------------------------------------------------------
# Curated legacy -> modern mapping.
#
# key: (prefix, sub_opcode) with prefix 0x00 = legacy core (unprefixed),
#      0xff = legacy ecma prefix.
# value: (modern Bytecode variant, [operand tokens])
#
# Coverage notes:
#  - Every legacy opcode observed in the 11 wild 0.0.0.2 packages is mapped.
#  - Legacy Java-era core opcodes (movi/ldarr/call.virt/...) and ecma
#    opcodes with no modern counterpart (debugger, expdyn, iternext,
#    copymodule, newobjspreaddyn, ldfunction, newlexenvwithnamedyn) are
#    intentionally unmapped: they decode to InvalidOpcode, same as before.
#  - definefuncdyn / definencfuncdyn / definegeneratorfunc / defineasyncfunc /
#    defineasyncgeneratorfunc all map to modern `Definefunc`: the
#    2022-08-18 ISA refactoring merged them, moving the distinction into the
#    method header's function-kind field (which abcd-file decodes
#    separately). The legacy trailing lexenv register operand has no modern
#    counterpart (modern definefunc reads the frame env) and is dropped.
# ---------------------------------------------------------------------------

CORE = 0x00
ECMA = 0xFF

MAPPING = {
    # --- legacy core: dynamic-subset + jumps (layouts unchanged) ---
    (CORE, 0x00): ("Nop", []),
    (CORE, 0x18): ("LdaStr", ["id"]),  # id32: direct string file offset
    (CORE, 0x22): ("Jmp", ["jmp"]),
    (CORE, 0x23): ("Jmp", ["jmp"]),
    (CORE, 0x2D): ("Jeqz", ["jmp"]),
    (CORE, 0x2E): ("Jeqz", ["jmp"]),
    (CORE, 0x2F): ("Jnez", ["jmp"]),
    (CORE, 0x30): ("Jnez", ["jmp"]),
    (CORE, 0xA0): ("Mov", ["v0", "v1"]),
    (CORE, 0xA1): ("Mov", ["v0", "v1"]),
    (CORE, 0xA2): ("Lda", ["v0"]),
    (CORE, 0xA3): ("Sta", ["v0"]),
    (CORE, 0xA4): ("Ldai", ["imm"]),
    (CORE, 0xA5): ("Fldai", ["imm"]),  # f64 bits, same as modern Imm
    (CORE, 0xA6): ("Return", []),

    # --- ecma: no-operand constants and friends (identical layouts) ---
    (ECMA, 0x00): ("Ldnan", []),
    (ECMA, 0x01): ("Ldinfinity", []),
    (ECMA, 0x03): ("Ldundefined", []),
    (ECMA, 0x04): ("Ldnull", []),
    (ECMA, 0x05): ("Ldsymbol", []),
    (ECMA, 0x06): ("Ldglobal", []),
    (ECMA, 0x07): ("Ldtrue", []),
    (ECMA, 0x08): ("Ldfalse", []),
    (ECMA, 0x09): ("Throw", []),
    (ECMA, 0x0D): ("Getunmappedargs", []),
    (ECMA, 0x0E): ("Getpropiterator", []),
    (ECMA, 0x0F): ("Asyncfunctionenter", []),
    (ECMA, 0x10): ("Ldhole", []),
    (ECMA, 0x11): ("Returnundefined", []),
    (ECMA, 0x12): ("Createemptyobject", []),
    # modern gained a trailing IC-slot immediate
    (ECMA, 0x0A): ("Typeof", ["0"]),
    (ECMA, 0x13): ("Createemptyarray", ["0"]),
    (ECMA, 0x14): ("Getiterator", ["0"]),
    # throw.* prefix (identical layouts)
    (ECMA, 0x15): ("ThrowNotexists", []),
    (ECMA, 0x16): ("ThrowPatternnoncoercible", []),
    (ECMA, 0x18): ("ThrowDeletesuperproperty", []),
    (ECMA, 0x38): ("ThrowConstassignment", ["v0"]),
    (ECMA, 0x3C): ("ThrowIfnotobject", ["v0"]),
    (ECMA, 0x46): ("ThrowUndefinedifhole", ["v0", "v1"]),
    (ECMA, 0x68): ("ThrowIfsupernotcorrectcall", ["imm"]),
    # deprecated.* prefix (identical operand layouts, explicit registers)
    (ECMA, 0x0B): ("DeprecatedLdlexenv", []),
    (ECMA, 0x0C): ("DeprecatedPoplexenv", []),
    (ECMA, 0x17): ("DeprecatedLdhomeobject", []),
    (ECMA, 0x2B): ("DeprecatedTonumber", ["v0"]),
    (ECMA, 0x2C): ("DeprecatedNeg", ["v0"]),
    (ECMA, 0x2D): ("DeprecatedNot", ["v0"]),
    (ECMA, 0x2E): ("DeprecatedInc", ["v0"]),
    (ECMA, 0x2F): ("DeprecatedDec", ["v0"]),
    (ECMA, 0x35): ("DeprecatedResumegenerator", ["v0"]),
    (ECMA, 0x36): ("DeprecatedGetresumemode", ["v0"]),
    (ECMA, 0x39): ("DeprecatedGettemplateobject", ["v0"]),
    (ECMA, 0x3B): ("DeprecatedCallarg0", ["v0"]),
    (ECMA, 0x41): ("DeprecatedDelobjprop", ["v0", "v1"]),
    (ECMA, 0x44): ("DeprecatedSuspendgenerator", ["v0", "v1"]),
    (ECMA, 0x45): ("DeprecatedAsyncfunctionawaituncaught", ["v0", "v1"]),
    (ECMA, 0x47): ("DeprecatedCallarg1", ["v0", "v1"]),
    (ECMA, 0x48): ("DeprecatedCopydataproperties", ["v0", "v1"]),
    (ECMA, 0x4A): ("DeprecatedGetiteratornext", ["v0", "v1"]),
    (ECMA, 0x4B): ("DeprecatedSetobjectwithproto", ["v0", "v1"]),
    (ECMA, 0x4C): ("DeprecatedLdobjbyvalue", ["v0", "v1"]),
    (ECMA, 0x4F): ("DeprecatedLdsuperbyvalue", ["v0", "v1"]),
    (ECMA, 0x51): ("DeprecatedLdobjbyindex", ["v0", "imm"]),
    (ECMA, 0x54): ("DeprecatedCallspread", ["v0", "v1", "v2"]),
    (ECMA, 0x55): ("DeprecatedAsyncfunctionresolve", ["v0", "v1", "v2"]),
    (ECMA, 0x56): ("DeprecatedAsyncfunctionreject", ["v0", "v1", "v2"]),
    (ECMA, 0x57): ("DeprecatedCallargs2", ["v0", "v1", "v2"]),
    (ECMA, 0x58): ("DeprecatedCallargs3", ["v0", "v1", "v2", "v3"]),
    (ECMA, 0x66): ("DeprecatedCreatearraywithbuffer", ["imm"]),  # global litarray idx
    (ECMA, 0x67): ("DeprecatedCreateobjecthavingmethod", ["imm"]),
    (ECMA, 0x69): ("DeprecatedCreateobjectwithbuffer", ["imm"]),
    (ECMA, 0x70): ("DeprecatedDefineclasswithbuffer",
                   ["id", "imm", "imm", "v0", "v1"]),  # id16 method idx, imm1 litarray idx
    (ECMA, 0x71): ("DeprecatedGetmodulenamespace", ["id"]),  # id32 string offset
    (ECMA, 0x72): ("DeprecatedStmodulevar", ["id"]),
    (ECMA, 0x77): ("DeprecatedLdobjbyname", ["id", "v0"]),
    (ECMA, 0x7A): ("DeprecatedLdsuperbyname", ["id", "v0"]),
    (ECMA, 0x7C): ("DeprecatedLdmodulevar", ["id", "imm"]),
    (ECMA, 0x80): ("DeprecatedStconsttoglobalrecord", ["id"]),
    (ECMA, 0x81): ("DeprecatedStlettoglobalrecord", ["id"]),
    (ECMA, 0x82): ("DeprecatedStclasstoglobalrecord", ["id"]),
    (ECMA, 0x88): ("DeprecatedTonumeric", ["v0"]),
    (ECMA, 0x8C): ("DeprecatedDynamicimport", ["v0"]),
    (ECMA, 0x8F): ("DeprecatedAsyncgeneratorreject", ["v0", "v1"]),
    # plain modern variants, identical layouts
    (ECMA, 0x37): ("Creategeneratorobj", ["v0"]),
    (ECMA, 0x3A): ("Getnextpropname", ["v0"]),
    (ECMA, 0x43): ("Createiterresultobj", ["v0", "v1"]),
    (ECMA, 0x49): ("Starrayspread", ["v0", "v1"]),
    (ECMA, 0x59): ("Definegettersetterbyvalue", ["v0", "v1", "v2", "v3"]),
    (ECMA, 0x6A): ("Ldlexvar", ["imm", "imm"]),  # imm4_imm4
    (ECMA, 0x6B): ("Ldlexvar", ["imm", "imm"]),  # imm8_imm8
    (ECMA, 0x6C): ("WideLdlexvar", ["imm", "imm"]),  # imm16_imm16
    (ECMA, 0x6D): ("DeprecatedStlexvar", ["imm", "imm", "v0"]),  # imm4_imm4_v8
    (ECMA, 0x6E): ("DeprecatedStlexvar", ["imm", "imm", "v0"]),  # imm8_imm8_v8
    (ECMA, 0x6F): ("DeprecatedStlexvar", ["imm", "imm", "v0"]),  # imm16_imm16_v8
    (ECMA, 0x7E): ("Istrue", []),
    (ECMA, 0x7F): ("Isfalse", []),
    (ECMA, 0x89): ("Createasyncgeneratorobj", ["v0"]),
    (ECMA, 0x8A): ("Asyncgeneratorresolve", ["v0", "v1", "v2"]),
    (ECMA, 0x90): ("CallruntimeNotifyconcurrentresult", []),
    # plain modern variants, IC-slot immediate synthesized as 0
    (ECMA, 0x1A): ("Add2", ["0", "v0"]),
    (ECMA, 0x1B): ("Sub2", ["0", "v0"]),
    (ECMA, 0x1C): ("Mul2", ["0", "v0"]),
    (ECMA, 0x1D): ("Div2", ["0", "v0"]),
    (ECMA, 0x1E): ("Mod2", ["0", "v0"]),
    (ECMA, 0x1F): ("Eq", ["0", "v0"]),
    (ECMA, 0x20): ("Noteq", ["0", "v0"]),
    (ECMA, 0x21): ("Less", ["0", "v0"]),
    (ECMA, 0x22): ("Lesseq", ["0", "v0"]),
    (ECMA, 0x23): ("Greater", ["0", "v0"]),
    (ECMA, 0x24): ("Greatereq", ["0", "v0"]),
    (ECMA, 0x25): ("Shl2", ["0", "v0"]),
    (ECMA, 0x26): ("Shr2", ["0", "v0"]),
    (ECMA, 0x27): ("Ashr2", ["0", "v0"]),
    (ECMA, 0x28): ("And2", ["0", "v0"]),
    (ECMA, 0x29): ("Or2", ["0", "v0"]),
    (ECMA, 0x2A): ("Xor2", ["0", "v0"]),
    (ECMA, 0x31): ("Isin", ["0", "v0"]),
    (ECMA, 0x32): ("Instanceof", ["0", "v0"]),
    (ECMA, 0x33): ("Strictnoteq", ["0", "v0"]),
    (ECMA, 0x34): ("Stricteq", ["0", "v0"]),
    (ECMA, 0x3E): ("Closeiterator", ["0", "v0"]),
    (ECMA, 0x40): ("Supercallspread", ["0", "v0"]),
    (ECMA, 0x4D): ("Stobjbyvalue", ["0", "v0", "v1"]),
    (ECMA, 0x4E): ("Stownbyvalue", ["0", "v0", "v1"]),
    (ECMA, 0x50): ("Stsuperbyvalue", ["0", "v0", "v1"]),
    (ECMA, 0x5E): ("Createobjectwithexcludedkeys", ["imm", "v0", "v1"]),
    (ECMA, 0x83): ("Stownbyvaluewithnameset", ["0", "v0", "v1"]),
    # range calls: legacy imm16 = arg count; modern adds IC slot and narrows
    # the count to u8 (value preserved in Imm)
    (ECMA, 0x5A): ("Newobjrange", ["0", "imm", "v0"]),
    (ECMA, 0x5B): ("Callrange", ["0", "imm", "v0"]),
    (ECMA, 0x5C): ("Callthisrange", ["0", "imm", "v0"]),
    (ECMA, 0x5D): ("Supercallthisrange", ["0", "imm", "v0"]),
    # define* family: merged into modern definefunc/definemethod (function
    # kind lives in the method header); trailing lexenv register dropped
    (ECMA, 0x5F): ("Definefunc", ["0", "id", "imm"]),
    (ECMA, 0x60): ("Definefunc", ["0", "id", "imm"]),
    (ECMA, 0x61): ("Definefunc", ["0", "id", "imm"]),
    (ECMA, 0x62): ("Definefunc", ["0", "id", "imm"]),
    (ECMA, 0x8B): ("Definefunc", ["0", "id", "imm"]),
    (ECMA, 0x63): ("Definemethod", ["0", "id", "imm"]),
    # imm16 -> modern imm8 (value preserved in Imm)
    (ECMA, 0x64): ("Newlexenv", ["imm"]),
    (ECMA, 0x65): ("Copyrestargs", ["imm"]),
    # string id32 (direct file offset) -> modern (ic imm, EntityId)
    (ECMA, 0x73): ("Tryldglobalbyname", ["0", "id"]),
    (ECMA, 0x74): ("Trystglobalbyname", ["0", "id"]),
    (ECMA, 0x75): ("Ldglobalvar", ["0", "id"]),
    (ECMA, 0x76): ("Stglobalvar", ["0", "id"]),
    (ECMA, 0x78): ("Stobjbyname", ["0", "id", "v0"]),
    (ECMA, 0x79): ("Stownbyname", ["0", "id", "v0"]),
    (ECMA, 0x7B): ("Stsuperbyname", ["0", "id", "v0"]),
    (ECMA, 0x84): ("Stownbynamewithnameset", ["0", "id", "v0"]),
    (ECMA, 0x87): ("Ldbigint", ["id"]),
    (ECMA, 0x7D): ("Createregexpwithliteral", ["0", "id", "imm"]),
    # v8_imm32: modern narrows the u32 index immediate to u16 (value kept)
    (ECMA, 0x52): ("Stobjbyindex", ["0", "v0", "imm"]),
    (ECMA, 0x53): ("Stownbyindex", ["0", "v0", "imm"]),
    # hot-patch ops survive only as wide.* in the modern ISA
    (ECMA, 0x8D): ("WideLdpatchvar", ["imm"]),
    (ECMA, 0x8E): ("WideStpatchvar", ["imm"]),
}

# ---------------------------------------------------------------------------

def parse_table(path):
    prefixes = {}
    insns = []
    for line in open(path):
        line = line.rstrip("\n")
        if line.startswith("PREFIX|"):
            _, name, idx = line.split("|")
            prefixes[name] = int(idx)
        elif line.startswith("INSN|"):
            _, sig, prefix, idx, fmt, size, ops, acc, props = line.split("|")
            operands = []
            if ops:
                for o in ops.split(","):
                    name, srcdst, typ, width, offset = o.split(":")
                    operands.append(dict(name=name, type=typ,
                                         width=int(width), offset=int(offset)))
            insns.append(dict(sig=sig, prefix=None if prefix == "-" else prefix,
                              idx=int(idx), fmt=fmt, size=int(size),
                              operands=operands))
    return prefixes, insns


def parse_variants(path):
    """Parse `VariantName(Field, ...)` lines from generated bytecode.rs."""
    variants = {}
    enum_re = re.compile(r"^    ([A-Z][A-Za-z0-9]*)(\(([^)]*)\))?,\s*$")
    in_enum = False
    for line in open(path):
        if line.startswith("pub enum Bytecode"):
            in_enum = True
            continue
        if in_enum:
            if line.startswith("}"):
                break
            m = enum_re.match(line.rstrip("\n"))
            if m:
                fields = m.group(3).split(", ") if m.group(3) else []
                variants[m.group(1)] = fields
    return variants


def gen_extractor(op, signed):
    """Rust expression reading legacy operand `op` from `b` (insn start)."""
    off, width = op["offset"], op["width"]
    byte = off // 8
    if width == 4:
        return f"(b[{byte}] >> 4) & 0xf" if off % 8 else f"b[{byte}] & 0xf"
    if width == 8:
        return f"b[{byte}]"
    if width == 16:
        return f"u16::from_le_bytes([b[{byte}], b[{byte + 1}]])"
    if width == 32:
        return (f"u32::from_le_bytes([b[{byte}], b[{byte + 1}], "
                f"b[{byte + 2}], b[{byte + 3}]])")
    if width == 64:
        return (f"u64::from_le_bytes([b[{byte}], b[{byte + 1}], b[{byte + 2}], "
                f"b[{byte + 3}], b[{byte + 4}], b[{byte + 5}], b[{byte + 6}], "
                f"b[{byte + 7}]])")
    raise ValueError(f"unsupported width {width}")


def main():
    old_path, variants_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    old_prefixes, old = parse_table(old_path)
    variants = parse_variants(variants_path)
    assert old_prefixes.get("ecma") == 0xFF, "ecma prefix must be 0xff"

    old_by_key = {}
    for i in old:
        if i["prefix"] is None:
            old_by_key[(0x00, i["idx"])] = i
        elif i["prefix"] == "ecma":
            old_by_key[(0xFF, i["idx"])] = i
        # legacy f32/cast/unsigned/bit prefixes (Java-era): never mapped

    lines = []
    emit = lines.append
    emit("// @generated by abcd-isa/tools/gen_legacy_table.py — do not edit.")
    emit("//")
    emit("// Legacy (file format 0.0.0.2, OpenHarmony 3.0/3.1-era) opcode")
    emit("// translation table. Maps legacy opcodes onto modern `Bytecode` IR")
    emit("// variants. See the generator for provenance and the curated mapping.")
    emit("")
    emit("use abcd_isa_sys::{Bytecode, EntityId, Imm, Label, Reg};")
    emit("")
    emit("/// One legacy opcode table entry.")
    emit("#[derive(Clone, Copy)]")
    emit("pub(crate) struct LegacyInsn {")
    emit("    /// Total instruction size in bytes (legacy encoding).")
    emit("    pub size: u8,")
    emit("    /// Build the modern-IR instruction from the raw bytes starting at")
    emit("    /// the instruction. Returns the instruction plus the raw jump")
    emit("    /// offset for jump instructions (resolved by the caller).")
    emit("    pub make: fn(&[u8]) -> (Bytecode, Option<i64>),")
    emit("}")
    emit("")

    errors = []
    for key in sorted(MAPPING):
        pbyte, sub = key
        old_insn = old_by_key.get(key)
        if old_insn is None:
            errors.append(f"{key}: not in legacy table")
            continue
        variant, tokens = MAPPING[key]
        fields = variants.get(variant)
        if fields is None:
            errors.append(f"{key}: variant {variant} not in generated Bytecode")
            continue
        if len(fields) != len(tokens):
            errors.append(f"{key}: {variant} takes {len(fields)} operands, "
                          f"{len(tokens)} tokens")
            continue

        old_ops = old_insn["operands"]
        old_vs = [o for o in old_ops if o["name"] == "v"]
        old_imms = [o for o in old_ops if o["name"] == "imm"]
        old_ids = [o for o in old_ops if o["name"].endswith("id")]
        imm_i = 0
        args = []
        jump = None
        consumed = 0
        for field, tok in zip(fields, tokens):
            if tok == "0":
                assert field == "Imm", f"{key}: synth imm into {field}"
                args.append("Imm(0)")
            elif tok.startswith("v"):
                op = old_vs[int(tok[1:])]
                assert field == "Reg", f"{key}: {variant} field {field} != Reg"
                args.append(f"Reg({gen_extractor(op, False)} as u16)")
                consumed += 1
            elif tok == "imm":
                op = old_imms[imm_i]
                assert field == "Imm", f"{key}: {variant} field {field} != Imm"
                signed = op["type"].startswith("i") or op["type"].startswith("f")
                ex = gen_extractor(op, signed)
                if op["width"] == 64:
                    args.append(f"Imm({ex} as i64)")  # f64 bits
                elif signed:
                    args.append(f"Imm(({ex}) as i{op['width']} as i64)")
                else:
                    args.append(f"Imm(({ex}) as i64)")
                imm_i += 1
                consumed += 1
            elif tok == "id":
                op = old_ids[0]
                old_ids.pop(0)
                assert field == "EntityId", f"{key}: {variant} field {field}"
                args.append(f"EntityId(({gen_extractor(op, False)}) as u32)")
                consumed += 1
            elif tok == "jmp":
                op = next(o for o in old_ops if o["name"] == "imm")
                assert field == "Label"
                args.append("Label(0)")
                ex = gen_extractor(op, True)
                jump = f"Some(({ex}) as i{op['width']} as i64)"
                consumed += 1
            else:
                raise ValueError(f"unknown token {tok}")
        # every legacy operand must be consumed exactly once (except the
        # documented define*/definemethod lexenv-register drop)
        if consumed != len(old_ops) and variant not in ("Definefunc", "Definemethod"):
            errors.append(f"{key}: consumed {consumed} of {len(old_ops)} "
                          f"legacy operands")
            continue

        fname = f"mk_{'core' if pbyte == 0 else 'ecma'}_{sub:02x}"
        sig = old_insn["sig"]
        ctor = f"Bytecode::{variant}({', '.join(args)})" if args else f"Bytecode::{variant}"
        reads_bytes = any(t != "0" for t in tokens)
        param = "b: &[u8]" if reads_bytes else "_b: &[u8]"
        emit(f"/// legacy `{sig}` [{old_insn['fmt']}] -> `{variant}`")
        emit(f"fn {fname}({param}) -> (Bytecode, Option<i64>) {{")
        emit(f"    ({ctor}, {jump if jump else 'None'})")
        emit("}")
        emit("")

    if errors:
        for e in errors:
            print("ERROR:", e, file=sys.stderr)
        sys.exit(1)

    for pbyte, name in ((0x00, "LEGACY_CORE"), (0xFF, "LEGACY_ECMA")):
        emit(f"/// Legacy {'core (unprefixed)' if pbyte == 0 else '0xff-prefixed ecma'} opcode table.")
        emit(f"pub(crate) static {name}: [Option<LegacyInsn>; 256] = {{")
        emit("    let mut t = [None; 256];")
        for (p, sub), (variant, _tokens) in sorted(MAPPING.items()):
            if p != pbyte:
                continue
            old_insn = old_by_key[(p, sub)]
            emit(f"    t[0x{sub:02x}] = Some(LegacyInsn {{ size: "
                 f"{old_insn['size']}, make: mk_{'core' if p == 0 else 'ecma'}_{sub:02x} }});")
        emit("    t")
        emit("};")
        emit("")

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {out_path}: {len(MAPPING)} legacy opcodes")


if __name__ == "__main__":
    main()
