// @generated by abcd-isa/tools/gen_legacy_table.py — do not edit.
//
// Legacy (file format 0.0.0.2, OpenHarmony 3.0/3.1-era) opcode
// translation table. Maps legacy opcodes onto modern `Bytecode` IR
// variants. See the generator for provenance and the curated mapping.

use abcd_isa_sys::{Bytecode, EntityId, Imm, Label, Reg};

/// One legacy opcode table entry.
#[derive(Clone, Copy)]
pub(crate) struct LegacyInsn {
    /// Total instruction size in bytes (legacy encoding).
    pub size: u8,
    /// Build the modern-IR instruction from the raw bytes starting at
    /// the instruction. Returns the instruction plus the raw jump
    /// offset for jump instructions (resolved by the caller).
    pub make: fn(&[u8]) -> (Bytecode, Option<i64>),
}

/// legacy `nop` [none] -> `Nop`
fn mk_core_00(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Nop, None)
}

/// legacy `lda.str string_id` [id32] -> `LdaStr`
fn mk_core_18(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::LdaStr(EntityId(
            (u32::from_le_bytes([b[1], b[2], b[3], b[4]])) as u32,
        )),
        None,
    )
}

/// legacy `jmp imm:i32` [imm8] -> `Jmp`
fn mk_core_22(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Jmp(Label(0)), Some((b[1]) as i8 as i64))
}

/// legacy `jmp imm:i32` [imm16] -> `Jmp`
fn mk_core_23(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Jmp(Label(0)),
        Some((u16::from_le_bytes([b[1], b[2]])) as i16 as i64),
    )
}

/// legacy `jeqz imm:i32` [imm8] -> `Jeqz`
fn mk_core_2d(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Jeqz(Label(0)), Some((b[1]) as i8 as i64))
}

/// legacy `jeqz imm:i32` [imm16] -> `Jeqz`
fn mk_core_2e(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Jeqz(Label(0)),
        Some((u16::from_le_bytes([b[1], b[2]])) as i16 as i64),
    )
}

/// legacy `jnez imm:i32` [imm8] -> `Jnez`
fn mk_core_2f(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Jnez(Label(0)), Some((b[1]) as i8 as i64))
}

/// legacy `jnez imm:i32` [imm16] -> `Jnez`
fn mk_core_30(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Jnez(Label(0)),
        Some((u16::from_le_bytes([b[1], b[2]])) as i16 as i64),
    )
}

/// legacy `mov.dyn v1:out:any, v2:in:any` [v8_v8] -> `Mov`
fn mk_core_a0(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Mov(Reg(b[1] as u16), Reg(b[2] as u16)), None)
}

/// legacy `mov.dyn v1:out:any, v2:in:any` [v16_v16] -> `Mov`
fn mk_core_a1(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Mov(
            Reg(u16::from_le_bytes([b[1], b[2]]) as u16),
            Reg(u16::from_le_bytes([b[3], b[4]]) as u16),
        ),
        None,
    )
}

/// legacy `lda.dyn v:in:any` [v8] -> `Lda`
fn mk_core_a2(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Lda(Reg(b[1] as u16)), None)
}

/// legacy `sta.dyn v:out:any` [v8] -> `Sta`
fn mk_core_a3(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Sta(Reg(b[1] as u16)), None)
}

/// legacy `ldai.dyn imm:i32` [imm32] -> `Ldai`
fn mk_core_a4(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Ldai(Imm(
            (u32::from_le_bytes([b[1], b[2], b[3], b[4]])) as i32 as i64
        )),
        None,
    )
}

/// legacy `fldai.dyn imm:f64` [imm64] -> `Fldai`
fn mk_core_a5(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Fldai(Imm(
            u64::from_le_bytes([b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8]]) as i64,
        )),
        None,
    )
}

/// legacy `return.dyn` [none] -> `Return`
fn mk_core_a6(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Return, None)
}

/// legacy `ecma.ldnan` [pref_none] -> `Ldnan`
fn mk_ecma_00(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Ldnan, None)
}

/// legacy `ecma.ldinfinity` [pref_none] -> `Ldinfinity`
fn mk_ecma_01(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Ldinfinity, None)
}

/// legacy `ecma.ldundefined` [pref_none] -> `Ldundefined`
fn mk_ecma_03(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Ldundefined, None)
}

/// legacy `ecma.ldnull` [pref_none] -> `Ldnull`
fn mk_ecma_04(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Ldnull, None)
}

/// legacy `ecma.ldsymbol` [pref_none] -> `Ldsymbol`
fn mk_ecma_05(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Ldsymbol, None)
}

/// legacy `ecma.ldglobal` [pref_none] -> `Ldglobal`
fn mk_ecma_06(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Ldglobal, None)
}

/// legacy `ecma.ldtrue` [pref_none] -> `Ldtrue`
fn mk_ecma_07(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Ldtrue, None)
}

/// legacy `ecma.ldfalse` [pref_none] -> `Ldfalse`
fn mk_ecma_08(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Ldfalse, None)
}

/// legacy `ecma.throwdyn` [pref_none] -> `Throw`
fn mk_ecma_09(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Throw, None)
}

/// legacy `ecma.typeofdyn` [pref_none] -> `Typeof`
fn mk_ecma_0a(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Typeof(Imm(0)), None)
}

/// legacy `ecma.ldlexenvdyn` [pref_none] -> `DeprecatedLdlexenv`
fn mk_ecma_0b(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedLdlexenv, None)
}

/// legacy `ecma.poplexenvdyn` [pref_none] -> `DeprecatedPoplexenv`
fn mk_ecma_0c(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedPoplexenv, None)
}

/// legacy `ecma.getunmappedargs` [pref_none] -> `Getunmappedargs`
fn mk_ecma_0d(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Getunmappedargs, None)
}

/// legacy `ecma.getpropiterator` [pref_none] -> `Getpropiterator`
fn mk_ecma_0e(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Getpropiterator, None)
}

/// legacy `ecma.asyncfunctionenter` [pref_none] -> `Asyncfunctionenter`
fn mk_ecma_0f(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Asyncfunctionenter, None)
}

/// legacy `ecma.ldhole` [pref_none] -> `Ldhole`
fn mk_ecma_10(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Ldhole, None)
}

/// legacy `ecma.returnundefined` [pref_none] -> `Returnundefined`
fn mk_ecma_11(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Returnundefined, None)
}

/// legacy `ecma.createemptyobject` [pref_none] -> `Createemptyobject`
fn mk_ecma_12(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Createemptyobject, None)
}

/// legacy `ecma.createemptyarray` [pref_none] -> `Createemptyarray`
fn mk_ecma_13(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Createemptyarray(Imm(0)), None)
}

/// legacy `ecma.getiterator` [pref_none] -> `Getiterator`
fn mk_ecma_14(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Getiterator(Imm(0)), None)
}

/// legacy `ecma.throwthrownotexists` [pref_none] -> `ThrowNotexists`
fn mk_ecma_15(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::ThrowNotexists, None)
}

/// legacy `ecma.throwpatternnoncoercible` [pref_none] -> `ThrowPatternnoncoercible`
fn mk_ecma_16(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::ThrowPatternnoncoercible, None)
}

/// legacy `ecma.ldhomeobject` [pref_none] -> `DeprecatedLdhomeobject`
fn mk_ecma_17(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedLdhomeobject, None)
}

/// legacy `ecma.throwdeletesuperproperty` [pref_none] -> `ThrowDeletesuperproperty`
fn mk_ecma_18(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::ThrowDeletesuperproperty, None)
}

/// legacy `ecma.add2dyn v:in:top` [pref_v8] -> `Add2`
fn mk_ecma_1a(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Add2(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.sub2dyn v:in:top` [pref_v8] -> `Sub2`
fn mk_ecma_1b(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Sub2(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.mul2dyn v:in:top` [pref_v8] -> `Mul2`
fn mk_ecma_1c(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Mul2(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.div2dyn v:in:top` [pref_v8] -> `Div2`
fn mk_ecma_1d(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Div2(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.mod2dyn v:in:top` [pref_v8] -> `Mod2`
fn mk_ecma_1e(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Mod2(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.eqdyn v:in:top` [pref_v8] -> `Eq`
fn mk_ecma_1f(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Eq(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.noteqdyn v:in:top` [pref_v8] -> `Noteq`
fn mk_ecma_20(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Noteq(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.lessdyn v:in:top` [pref_v8] -> `Less`
fn mk_ecma_21(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Less(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.lesseqdyn v:in:top` [pref_v8] -> `Lesseq`
fn mk_ecma_22(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Lesseq(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.greaterdyn v:in:top` [pref_v8] -> `Greater`
fn mk_ecma_23(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Greater(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.greatereqdyn v:in:top` [pref_v8] -> `Greatereq`
fn mk_ecma_24(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Greatereq(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.shl2dyn v:in:top` [pref_v8] -> `Shl2`
fn mk_ecma_25(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Shl2(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.shr2dyn v:in:top` [pref_v8] -> `Shr2`
fn mk_ecma_26(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Shr2(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.ashr2dyn v:in:top` [pref_v8] -> `Ashr2`
fn mk_ecma_27(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Ashr2(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.and2dyn v:in:top` [pref_v8] -> `And2`
fn mk_ecma_28(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::And2(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.or2dyn v:in:top` [pref_v8] -> `Or2`
fn mk_ecma_29(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Or2(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.xor2dyn v:in:top` [pref_v8] -> `Xor2`
fn mk_ecma_2a(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Xor2(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.tonumber v:in:top` [pref_v8] -> `DeprecatedTonumber`
fn mk_ecma_2b(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedTonumber(Reg(b[2] as u16)), None)
}

/// legacy `ecma.negdyn v:in:top` [pref_v8] -> `DeprecatedNeg`
fn mk_ecma_2c(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedNeg(Reg(b[2] as u16)), None)
}

/// legacy `ecma.notdyn v:in:top` [pref_v8] -> `DeprecatedNot`
fn mk_ecma_2d(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedNot(Reg(b[2] as u16)), None)
}

/// legacy `ecma.incdyn v:in:top` [pref_v8] -> `DeprecatedInc`
fn mk_ecma_2e(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedInc(Reg(b[2] as u16)), None)
}

/// legacy `ecma.decdyn v:in:top` [pref_v8] -> `DeprecatedDec`
fn mk_ecma_2f(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedDec(Reg(b[2] as u16)), None)
}

/// legacy `ecma.isindyn v:in:top` [pref_v8] -> `Isin`
fn mk_ecma_31(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Isin(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.instanceofdyn v:in:top` [pref_v8] -> `Instanceof`
fn mk_ecma_32(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Instanceof(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.strictnoteqdyn v:in:top` [pref_v8] -> `Strictnoteq`
fn mk_ecma_33(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Strictnoteq(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.stricteqdyn v:in:top` [pref_v8] -> `Stricteq`
fn mk_ecma_34(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Stricteq(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.resumegenerator v:in:top` [pref_v8] -> `DeprecatedResumegenerator`
fn mk_ecma_35(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedResumegenerator(Reg(b[2] as u16)), None)
}

/// legacy `ecma.getresumemode v:in:top` [pref_v8] -> `DeprecatedGetresumemode`
fn mk_ecma_36(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedGetresumemode(Reg(b[2] as u16)), None)
}

/// legacy `ecma.creategeneratorobj v:in:top` [pref_v8] -> `Creategeneratorobj`
fn mk_ecma_37(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Creategeneratorobj(Reg(b[2] as u16)), None)
}

/// legacy `ecma.throwconstassignment v:in:top` [pref_v8] -> `ThrowConstassignment`
fn mk_ecma_38(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::ThrowConstassignment(Reg(b[2] as u16)), None)
}

/// legacy `ecma.gettemplateobject v:in:top` [pref_v8] -> `DeprecatedGettemplateobject`
fn mk_ecma_39(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedGettemplateobject(Reg(b[2] as u16)),
        None,
    )
}

/// legacy `ecma.getnextpropname v:in:top` [pref_v8] -> `Getnextpropname`
fn mk_ecma_3a(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Getnextpropname(Reg(b[2] as u16)), None)
}

/// legacy `ecma.callarg0dyn v:in:top` [pref_v8] -> `DeprecatedCallarg0`
fn mk_ecma_3b(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedCallarg0(Reg(b[2] as u16)), None)
}

/// legacy `ecma.throwifnotobject v:in:top` [pref_v8] -> `ThrowIfnotobject`
fn mk_ecma_3c(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::ThrowIfnotobject(Reg(b[2] as u16)), None)
}

/// legacy `ecma.closeiterator v:in:top` [pref_v8] -> `Closeiterator`
fn mk_ecma_3e(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Closeiterator(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.supercallspread v:in:top` [pref_v8] -> `Supercallspread`
fn mk_ecma_40(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Supercallspread(Imm(0), Reg(b[2] as u16)), None)
}

/// legacy `ecma.delobjprop v1:in:top, v2:in:top` [pref_v8_v8] -> `DeprecatedDelobjprop`
fn mk_ecma_41(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedDelobjprop(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.createiterresultobj v1:in:top, v2:in:top` [pref_v8_v8] -> `Createiterresultobj`
fn mk_ecma_43(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Createiterresultobj(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.suspendgenerator v1:in:top, v2:in:top` [pref_v8_v8] -> `DeprecatedSuspendgenerator`
fn mk_ecma_44(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedSuspendgenerator(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.asyncfunctionawaituncaught v1:in:top, v2:in:top` [pref_v8_v8] -> `DeprecatedAsyncfunctionawaituncaught`
fn mk_ecma_45(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedAsyncfunctionawaituncaught(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.throwundefinedifhole v1:in:top, v2:in:top` [pref_v8_v8] -> `ThrowUndefinedifhole`
fn mk_ecma_46(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::ThrowUndefinedifhole(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.callarg1dyn v1:in:top, v2:in:top` [pref_v8_v8] -> `DeprecatedCallarg1`
fn mk_ecma_47(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedCallarg1(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.copydataproperties v1:in:top, v2:in:top` [pref_v8_v8] -> `DeprecatedCopydataproperties`
fn mk_ecma_48(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedCopydataproperties(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.starrayspread v1:in:top, v2:in:top` [pref_v8_v8] -> `Starrayspread`
fn mk_ecma_49(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Starrayspread(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.getiteratornext v1:in:top, v2:in:top` [pref_v8_v8] -> `DeprecatedGetiteratornext`
fn mk_ecma_4a(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedGetiteratornext(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.setobjectwithproto v1:in:top, v2:in:top` [pref_v8_v8] -> `DeprecatedSetobjectwithproto`
fn mk_ecma_4b(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedSetobjectwithproto(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.ldobjbyvalue v1:in:top, v2:in:top` [pref_v8_v8] -> `DeprecatedLdobjbyvalue`
fn mk_ecma_4c(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedLdobjbyvalue(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.stobjbyvalue v1:in:top, v2:in:top` [pref_v8_v8] -> `Stobjbyvalue`
fn mk_ecma_4d(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Stobjbyvalue(Imm(0), Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.stownbyvalue v1:in:top, v2:in:top` [pref_v8_v8] -> `Stownbyvalue`
fn mk_ecma_4e(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Stownbyvalue(Imm(0), Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.ldsuperbyvalue v1:in:top, v2:in:top` [pref_v8_v8] -> `DeprecatedLdsuperbyvalue`
fn mk_ecma_4f(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedLdsuperbyvalue(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.stsuperbyvalue v1:in:top, v2:in:top` [pref_v8_v8] -> `Stsuperbyvalue`
fn mk_ecma_50(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Stsuperbyvalue(Imm(0), Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.ldobjbyindex v:in:top, imm` [pref_v8_imm32] -> `DeprecatedLdobjbyindex`
fn mk_ecma_51(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedLdobjbyindex(
            Reg(b[2] as u16),
            Imm((u32::from_le_bytes([b[3], b[4], b[5], b[6]])) as i64),
        ),
        None,
    )
}

/// legacy `ecma.stobjbyindex v:in:top, imm` [pref_v8_imm32] -> `Stobjbyindex`
fn mk_ecma_52(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Stobjbyindex(
            Imm(0),
            Reg(b[2] as u16),
            Imm((u32::from_le_bytes([b[3], b[4], b[5], b[6]])) as i64),
        ),
        None,
    )
}

/// legacy `ecma.stownbyindex v:in:top, imm` [pref_v8_imm32] -> `Stownbyindex`
fn mk_ecma_53(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Stownbyindex(
            Imm(0),
            Reg(b[2] as u16),
            Imm((u32::from_le_bytes([b[3], b[4], b[5], b[6]])) as i64),
        ),
        None,
    )
}

/// legacy `ecma.callspreaddyn v1:in:top, v2:in:top, v3:in:top` [pref_v8_v8_v8] -> `DeprecatedCallspread`
fn mk_ecma_54(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedCallspread(Reg(b[2] as u16), Reg(b[3] as u16), Reg(b[4] as u16)),
        None,
    )
}

/// legacy `ecma.asyncfunctionresolve v1:in:top, v2:in:top, v3:in:top` [pref_v8_v8_v8] -> `DeprecatedAsyncfunctionresolve`
fn mk_ecma_55(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedAsyncfunctionresolve(
            Reg(b[2] as u16),
            Reg(b[3] as u16),
            Reg(b[4] as u16),
        ),
        None,
    )
}

/// legacy `ecma.asyncfunctionreject v1:in:top, v2:in:top, v3:in:top` [pref_v8_v8_v8] -> `DeprecatedAsyncfunctionreject`
fn mk_ecma_56(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedAsyncfunctionreject(
            Reg(b[2] as u16),
            Reg(b[3] as u16),
            Reg(b[4] as u16),
        ),
        None,
    )
}

/// legacy `ecma.callargs2dyn v1:in:top, v2:in:top, v3:in:top` [pref_v8_v8_v8] -> `DeprecatedCallargs2`
fn mk_ecma_57(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedCallargs2(Reg(b[2] as u16), Reg(b[3] as u16), Reg(b[4] as u16)),
        None,
    )
}

/// legacy `ecma.callargs3dyn v1:in:top, v2:in:top, v3:in:top, v4:in:top` [pref_v8_v8_v8_v8] -> `DeprecatedCallargs3`
fn mk_ecma_58(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedCallargs3(
            Reg(b[2] as u16),
            Reg(b[3] as u16),
            Reg(b[4] as u16),
            Reg(b[5] as u16),
        ),
        None,
    )
}

/// legacy `ecma.definegettersetterbyvalue v1:in:top, v2:in:top, v3:in:top, v4:in:top` [pref_v8_v8_v8_v8] -> `Definegettersetterbyvalue`
fn mk_ecma_59(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Definegettersetterbyvalue(
            Reg(b[2] as u16),
            Reg(b[3] as u16),
            Reg(b[4] as u16),
            Reg(b[5] as u16),
        ),
        None,
    )
}

/// legacy `ecma.newobjdynrange imm, v:in:top` [pref_imm16_v8] -> `Newobjrange`
fn mk_ecma_5a(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Newobjrange(
            Imm(0),
            Imm((u16::from_le_bytes([b[2], b[3]])) as i64),
            Reg(b[4] as u16),
        ),
        None,
    )
}

/// legacy `ecma.callirangedyn imm, v:in:top` [pref_imm16_v8] -> `Callrange`
fn mk_ecma_5b(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Callrange(
            Imm(0),
            Imm((u16::from_le_bytes([b[2], b[3]])) as i64),
            Reg(b[4] as u16),
        ),
        None,
    )
}

/// legacy `ecma.callithisrangedyn imm, v:in:top` [pref_imm16_v8] -> `Callthisrange`
fn mk_ecma_5c(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Callthisrange(
            Imm(0),
            Imm((u16::from_le_bytes([b[2], b[3]])) as i64),
            Reg(b[4] as u16),
        ),
        None,
    )
}

/// legacy `ecma.supercall imm, v:in:top` [pref_imm16_v8] -> `Supercallthisrange`
fn mk_ecma_5d(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Supercallthisrange(
            Imm(0),
            Imm((u16::from_le_bytes([b[2], b[3]])) as i64),
            Reg(b[4] as u16),
        ),
        None,
    )
}

/// legacy `ecma.createobjectwithexcludedkeys imm, v1:in:top, v2:in:top` [pref_imm16_v8_v8] -> `Createobjectwithexcludedkeys`
fn mk_ecma_5e(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Createobjectwithexcludedkeys(
            Imm((u16::from_le_bytes([b[2], b[3]])) as i64),
            Reg(b[4] as u16),
            Reg(b[5] as u16),
        ),
        None,
    )
}

/// legacy `ecma.definefuncdyn method_id, imm, v:in:top` [pref_id16_imm16_v8] -> `Definefunc`
fn mk_ecma_5f(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Definefunc(
            Imm(0),
            EntityId((u16::from_le_bytes([b[2], b[3]])) as u32),
            Imm((u16::from_le_bytes([b[4], b[5]])) as i64),
        ),
        None,
    )
}

/// legacy `ecma.definencfuncdyn method_id, imm, v:in:top` [pref_id16_imm16_v8] -> `Definefunc`
fn mk_ecma_60(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Definefunc(
            Imm(0),
            EntityId((u16::from_le_bytes([b[2], b[3]])) as u32),
            Imm((u16::from_le_bytes([b[4], b[5]])) as i64),
        ),
        None,
    )
}

/// legacy `ecma.definegeneratorfunc method_id, imm, v:in:top` [pref_id16_imm16_v8] -> `Definefunc`
fn mk_ecma_61(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Definefunc(
            Imm(0),
            EntityId((u16::from_le_bytes([b[2], b[3]])) as u32),
            Imm((u16::from_le_bytes([b[4], b[5]])) as i64),
        ),
        None,
    )
}

/// legacy `ecma.defineasyncfunc method_id, imm, v:in:top` [pref_id16_imm16_v8] -> `Definefunc`
fn mk_ecma_62(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Definefunc(
            Imm(0),
            EntityId((u16::from_le_bytes([b[2], b[3]])) as u32),
            Imm((u16::from_le_bytes([b[4], b[5]])) as i64),
        ),
        None,
    )
}

/// legacy `ecma.definemethod method_id, imm, v:in:top` [pref_id16_imm16_v8] -> `Definemethod`
fn mk_ecma_63(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Definemethod(
            Imm(0),
            EntityId((u16::from_le_bytes([b[2], b[3]])) as u32),
            Imm((u16::from_le_bytes([b[4], b[5]])) as i64),
        ),
        None,
    )
}

/// legacy `ecma.newlexenvdyn imm` [pref_imm16] -> `Newlexenv`
fn mk_ecma_64(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Newlexenv(Imm((u16::from_le_bytes([b[2], b[3]])) as i64)),
        None,
    )
}

/// legacy `ecma.copyrestargs imm` [pref_imm16] -> `Copyrestargs`
fn mk_ecma_65(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Copyrestargs(Imm((u16::from_le_bytes([b[2], b[3]])) as i64)),
        None,
    )
}

/// legacy `ecma.createarraywithbuffer imm` [pref_imm16] -> `DeprecatedCreatearraywithbuffer`
fn mk_ecma_66(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedCreatearraywithbuffer(Imm((u16::from_le_bytes([b[2], b[3]])) as i64)),
        None,
    )
}

/// legacy `ecma.createobjecthavingmethod imm` [pref_imm16] -> `DeprecatedCreateobjecthavingmethod`
fn mk_ecma_67(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedCreateobjecthavingmethod(
            Imm((u16::from_le_bytes([b[2], b[3]])) as i64),
        ),
        None,
    )
}

/// legacy `ecma.throwifsupernotcorrectcall imm` [pref_imm16] -> `ThrowIfsupernotcorrectcall`
fn mk_ecma_68(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::ThrowIfsupernotcorrectcall(Imm((u16::from_le_bytes([b[2], b[3]])) as i64)),
        None,
    )
}

/// legacy `ecma.createobjectwithbuffer imm` [pref_imm16] -> `DeprecatedCreateobjectwithbuffer`
fn mk_ecma_69(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedCreateobjectwithbuffer(Imm((u16::from_le_bytes([b[2], b[3]])) as i64)),
        None,
    )
}

/// legacy `ecma.ldlexvardyn imm1, imm2` [pref_imm4_imm4] -> `Ldlexvar`
fn mk_ecma_6a(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Ldlexvar(Imm((b[2] & 0xf) as i64), Imm(((b[2] >> 4) & 0xf) as i64)),
        None,
    )
}

/// legacy `ecma.ldlexvardyn imm1, imm2` [pref_imm8_imm8] -> `Ldlexvar`
fn mk_ecma_6b(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Ldlexvar(Imm((b[2]) as i64), Imm((b[3]) as i64)),
        None,
    )
}

/// legacy `ecma.ldlexvardyn imm1, imm2` [pref_imm16_imm16] -> `WideLdlexvar`
fn mk_ecma_6c(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::WideLdlexvar(
            Imm((u16::from_le_bytes([b[2], b[3]])) as i64),
            Imm((u16::from_le_bytes([b[4], b[5]])) as i64),
        ),
        None,
    )
}

/// legacy `ecma.stlexvardyn imm1, imm2, v:in:top` [pref_imm4_imm4_v8] -> `DeprecatedStlexvar`
fn mk_ecma_6d(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedStlexvar(
            Imm((b[2] & 0xf) as i64),
            Imm(((b[2] >> 4) & 0xf) as i64),
            Reg(b[3] as u16),
        ),
        None,
    )
}

/// legacy `ecma.stlexvardyn imm1, imm2, v:in:top` [pref_imm8_imm8_v8] -> `DeprecatedStlexvar`
fn mk_ecma_6e(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedStlexvar(Imm((b[2]) as i64), Imm((b[3]) as i64), Reg(b[4] as u16)),
        None,
    )
}

/// legacy `ecma.stlexvardyn imm1, imm2, v:in:top` [pref_imm16_imm16_v8] -> `DeprecatedStlexvar`
fn mk_ecma_6f(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedStlexvar(
            Imm((u16::from_le_bytes([b[2], b[3]])) as i64),
            Imm((u16::from_le_bytes([b[4], b[5]])) as i64),
            Reg(b[6] as u16),
        ),
        None,
    )
}

/// legacy `ecma.defineclasswithbuffer method_id, imm1, imm2, v1:in:top, v2:in:top` [pref_id16_imm16_imm16_v8_v8] -> `DeprecatedDefineclasswithbuffer`
fn mk_ecma_70(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedDefineclasswithbuffer(
            EntityId((u16::from_le_bytes([b[2], b[3]])) as u32),
            Imm((u16::from_le_bytes([b[4], b[5]])) as i64),
            Imm((u16::from_le_bytes([b[6], b[7]])) as i64),
            Reg(b[8] as u16),
            Reg(b[9] as u16),
        ),
        None,
    )
}

/// legacy `ecma.getmodulenamespace string_id` [pref_id32] -> `DeprecatedGetmodulenamespace`
fn mk_ecma_71(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedGetmodulenamespace(EntityId(
            (u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32,
        )),
        None,
    )
}

/// legacy `ecma.stmodulevar string_id` [pref_id32] -> `DeprecatedStmodulevar`
fn mk_ecma_72(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedStmodulevar(EntityId(
            (u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32,
        )),
        None,
    )
}

/// legacy `ecma.tryldglobalbyname string_id` [pref_id32] -> `Tryldglobalbyname`
fn mk_ecma_73(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Tryldglobalbyname(
            Imm(0),
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
        ),
        None,
    )
}

/// legacy `ecma.trystglobalbyname string_id` [pref_id32] -> `Trystglobalbyname`
fn mk_ecma_74(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Trystglobalbyname(
            Imm(0),
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
        ),
        None,
    )
}

/// legacy `ecma.ldglobalvar string_id` [pref_id32] -> `Ldglobalvar`
fn mk_ecma_75(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Ldglobalvar(
            Imm(0),
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
        ),
        None,
    )
}

/// legacy `ecma.stglobalvar string_id` [pref_id32] -> `Stglobalvar`
fn mk_ecma_76(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Stglobalvar(
            Imm(0),
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
        ),
        None,
    )
}

/// legacy `ecma.ldobjbyname string_id, v:in:top` [pref_id32_v8] -> `DeprecatedLdobjbyname`
fn mk_ecma_77(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedLdobjbyname(
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
            Reg(b[6] as u16),
        ),
        None,
    )
}

/// legacy `ecma.stobjbyname string_id, v:in:top` [pref_id32_v8] -> `Stobjbyname`
fn mk_ecma_78(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Stobjbyname(
            Imm(0),
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
            Reg(b[6] as u16),
        ),
        None,
    )
}

/// legacy `ecma.stownbyname string_id, v:in:top` [pref_id32_v8] -> `Stownbyname`
fn mk_ecma_79(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Stownbyname(
            Imm(0),
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
            Reg(b[6] as u16),
        ),
        None,
    )
}

/// legacy `ecma.ldsuperbyname string_id, v:in:top` [pref_id32_v8] -> `DeprecatedLdsuperbyname`
fn mk_ecma_7a(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedLdsuperbyname(
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
            Reg(b[6] as u16),
        ),
        None,
    )
}

/// legacy `ecma.stsuperbyname string_id, v:in:top` [pref_id32_v8] -> `Stsuperbyname`
fn mk_ecma_7b(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Stsuperbyname(
            Imm(0),
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
            Reg(b[6] as u16),
        ),
        None,
    )
}

/// legacy `ecma.ldmodulevar string_id, imm` [pref_id32_imm8] -> `DeprecatedLdmodulevar`
fn mk_ecma_7c(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedLdmodulevar(
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
            Imm((b[6]) as i64),
        ),
        None,
    )
}

/// legacy `ecma.createregexpwithliteral string_id, imm` [pref_id32_imm8] -> `Createregexpwithliteral`
fn mk_ecma_7d(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Createregexpwithliteral(
            Imm(0),
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
            Imm((b[6]) as i64),
        ),
        None,
    )
}

/// legacy `ecma.istrue` [pref_none] -> `Istrue`
fn mk_ecma_7e(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Istrue, None)
}

/// legacy `ecma.isfalse` [pref_none] -> `Isfalse`
fn mk_ecma_7f(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Isfalse, None)
}

/// legacy `ecma.stconsttoglobalrecord string_id` [pref_id32] -> `DeprecatedStconsttoglobalrecord`
fn mk_ecma_80(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedStconsttoglobalrecord(EntityId(
            (u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32,
        )),
        None,
    )
}

/// legacy `ecma.stlettoglobalrecord string_id` [pref_id32] -> `DeprecatedStlettoglobalrecord`
fn mk_ecma_81(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedStlettoglobalrecord(EntityId(
            (u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32,
        )),
        None,
    )
}

/// legacy `ecma.stclasstoglobalrecord string_id` [pref_id32] -> `DeprecatedStclasstoglobalrecord`
fn mk_ecma_82(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedStclasstoglobalrecord(EntityId(
            (u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32,
        )),
        None,
    )
}

/// legacy `ecma.stownbyvaluewithnameset v1:in:top, v2:in:top` [pref_v8_v8] -> `Stownbyvaluewithnameset`
fn mk_ecma_83(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Stownbyvaluewithnameset(Imm(0), Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.stownbynamewithnameset string_id, v:in:top` [pref_id32_v8] -> `Stownbynamewithnameset`
fn mk_ecma_84(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Stownbynamewithnameset(
            Imm(0),
            EntityId((u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32),
            Reg(b[6] as u16),
        ),
        None,
    )
}

/// legacy `ecma.ldbigint string_id` [pref_id32] -> `Ldbigint`
fn mk_ecma_87(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Ldbigint(EntityId(
            (u32::from_le_bytes([b[2], b[3], b[4], b[5]])) as u32,
        )),
        None,
    )
}

/// legacy `ecma.tonumeric v:in:top` [pref_v8] -> `DeprecatedTonumeric`
fn mk_ecma_88(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedTonumeric(Reg(b[2] as u16)), None)
}

/// legacy `ecma.createasyncgeneratorobj v:in:top` [pref_v8] -> `Createasyncgeneratorobj`
fn mk_ecma_89(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::Createasyncgeneratorobj(Reg(b[2] as u16)), None)
}

/// legacy `ecma.asyncgeneratorresolve v1:in:top, v2:in:top, v3:in:top` [pref_v8_v8_v8] -> `Asyncgeneratorresolve`
fn mk_ecma_8a(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Asyncgeneratorresolve(Reg(b[2] as u16), Reg(b[3] as u16), Reg(b[4] as u16)),
        None,
    )
}

/// legacy `ecma.defineasyncgeneratorfunc method_id, imm, v:in:top` [pref_id16_imm16_v8] -> `Definefunc`
fn mk_ecma_8b(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::Definefunc(
            Imm(0),
            EntityId((u16::from_le_bytes([b[2], b[3]])) as u32),
            Imm((u16::from_le_bytes([b[4], b[5]])) as i64),
        ),
        None,
    )
}

/// legacy `ecma.dynamicimport v:in:top` [pref_v8] -> `DeprecatedDynamicimport`
fn mk_ecma_8c(b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::DeprecatedDynamicimport(Reg(b[2] as u16)), None)
}

/// legacy `ecma.ldpatchvar imm` [pref_imm16] -> `WideLdpatchvar`
fn mk_ecma_8d(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::WideLdpatchvar(Imm((u16::from_le_bytes([b[2], b[3]])) as i64)),
        None,
    )
}

/// legacy `ecma.stpatchvar imm` [pref_imm16] -> `WideStpatchvar`
fn mk_ecma_8e(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::WideStpatchvar(Imm((u16::from_le_bytes([b[2], b[3]])) as i64)),
        None,
    )
}

/// legacy `ecma.asyncgeneratorreject v1:in:top, v2:in:top` [pref_v8_v8] -> `DeprecatedAsyncgeneratorreject`
fn mk_ecma_8f(b: &[u8]) -> (Bytecode, Option<i64>) {
    (
        Bytecode::DeprecatedAsyncgeneratorreject(Reg(b[2] as u16), Reg(b[3] as u16)),
        None,
    )
}

/// legacy `ecma.notifyconcurrentresult` [pref_none] -> `CallruntimeNotifyconcurrentresult`
fn mk_ecma_90(_b: &[u8]) -> (Bytecode, Option<i64>) {
    (Bytecode::CallruntimeNotifyconcurrentresult, None)
}

/// Legacy core (unprefixed) opcode table.
pub(crate) static LEGACY_CORE: [Option<LegacyInsn>; 256] = {
    let mut t = [None; 256];
    t[0x00] = Some(LegacyInsn {
        size: 1,
        make: mk_core_00,
    });
    t[0x18] = Some(LegacyInsn {
        size: 5,
        make: mk_core_18,
    });
    t[0x22] = Some(LegacyInsn {
        size: 2,
        make: mk_core_22,
    });
    t[0x23] = Some(LegacyInsn {
        size: 3,
        make: mk_core_23,
    });
    t[0x2d] = Some(LegacyInsn {
        size: 2,
        make: mk_core_2d,
    });
    t[0x2e] = Some(LegacyInsn {
        size: 3,
        make: mk_core_2e,
    });
    t[0x2f] = Some(LegacyInsn {
        size: 2,
        make: mk_core_2f,
    });
    t[0x30] = Some(LegacyInsn {
        size: 3,
        make: mk_core_30,
    });
    t[0xa0] = Some(LegacyInsn {
        size: 3,
        make: mk_core_a0,
    });
    t[0xa1] = Some(LegacyInsn {
        size: 5,
        make: mk_core_a1,
    });
    t[0xa2] = Some(LegacyInsn {
        size: 2,
        make: mk_core_a2,
    });
    t[0xa3] = Some(LegacyInsn {
        size: 2,
        make: mk_core_a3,
    });
    t[0xa4] = Some(LegacyInsn {
        size: 5,
        make: mk_core_a4,
    });
    t[0xa5] = Some(LegacyInsn {
        size: 9,
        make: mk_core_a5,
    });
    t[0xa6] = Some(LegacyInsn {
        size: 1,
        make: mk_core_a6,
    });
    t
};

/// Legacy 0xff-prefixed ecma opcode table.
pub(crate) static LEGACY_ECMA: [Option<LegacyInsn>; 256] = {
    let mut t = [None; 256];
    t[0x00] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_00,
    });
    t[0x01] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_01,
    });
    t[0x03] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_03,
    });
    t[0x04] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_04,
    });
    t[0x05] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_05,
    });
    t[0x06] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_06,
    });
    t[0x07] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_07,
    });
    t[0x08] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_08,
    });
    t[0x09] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_09,
    });
    t[0x0a] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_0a,
    });
    t[0x0b] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_0b,
    });
    t[0x0c] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_0c,
    });
    t[0x0d] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_0d,
    });
    t[0x0e] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_0e,
    });
    t[0x0f] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_0f,
    });
    t[0x10] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_10,
    });
    t[0x11] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_11,
    });
    t[0x12] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_12,
    });
    t[0x13] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_13,
    });
    t[0x14] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_14,
    });
    t[0x15] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_15,
    });
    t[0x16] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_16,
    });
    t[0x17] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_17,
    });
    t[0x18] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_18,
    });
    t[0x1a] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_1a,
    });
    t[0x1b] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_1b,
    });
    t[0x1c] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_1c,
    });
    t[0x1d] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_1d,
    });
    t[0x1e] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_1e,
    });
    t[0x1f] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_1f,
    });
    t[0x20] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_20,
    });
    t[0x21] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_21,
    });
    t[0x22] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_22,
    });
    t[0x23] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_23,
    });
    t[0x24] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_24,
    });
    t[0x25] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_25,
    });
    t[0x26] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_26,
    });
    t[0x27] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_27,
    });
    t[0x28] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_28,
    });
    t[0x29] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_29,
    });
    t[0x2a] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_2a,
    });
    t[0x2b] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_2b,
    });
    t[0x2c] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_2c,
    });
    t[0x2d] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_2d,
    });
    t[0x2e] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_2e,
    });
    t[0x2f] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_2f,
    });
    t[0x31] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_31,
    });
    t[0x32] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_32,
    });
    t[0x33] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_33,
    });
    t[0x34] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_34,
    });
    t[0x35] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_35,
    });
    t[0x36] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_36,
    });
    t[0x37] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_37,
    });
    t[0x38] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_38,
    });
    t[0x39] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_39,
    });
    t[0x3a] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_3a,
    });
    t[0x3b] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_3b,
    });
    t[0x3c] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_3c,
    });
    t[0x3e] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_3e,
    });
    t[0x40] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_40,
    });
    t[0x41] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_41,
    });
    t[0x43] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_43,
    });
    t[0x44] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_44,
    });
    t[0x45] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_45,
    });
    t[0x46] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_46,
    });
    t[0x47] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_47,
    });
    t[0x48] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_48,
    });
    t[0x49] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_49,
    });
    t[0x4a] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_4a,
    });
    t[0x4b] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_4b,
    });
    t[0x4c] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_4c,
    });
    t[0x4d] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_4d,
    });
    t[0x4e] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_4e,
    });
    t[0x4f] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_4f,
    });
    t[0x50] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_50,
    });
    t[0x51] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_51,
    });
    t[0x52] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_52,
    });
    t[0x53] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_53,
    });
    t[0x54] = Some(LegacyInsn {
        size: 5,
        make: mk_ecma_54,
    });
    t[0x55] = Some(LegacyInsn {
        size: 5,
        make: mk_ecma_55,
    });
    t[0x56] = Some(LegacyInsn {
        size: 5,
        make: mk_ecma_56,
    });
    t[0x57] = Some(LegacyInsn {
        size: 5,
        make: mk_ecma_57,
    });
    t[0x58] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_58,
    });
    t[0x59] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_59,
    });
    t[0x5a] = Some(LegacyInsn {
        size: 5,
        make: mk_ecma_5a,
    });
    t[0x5b] = Some(LegacyInsn {
        size: 5,
        make: mk_ecma_5b,
    });
    t[0x5c] = Some(LegacyInsn {
        size: 5,
        make: mk_ecma_5c,
    });
    t[0x5d] = Some(LegacyInsn {
        size: 5,
        make: mk_ecma_5d,
    });
    t[0x5e] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_5e,
    });
    t[0x5f] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_5f,
    });
    t[0x60] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_60,
    });
    t[0x61] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_61,
    });
    t[0x62] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_62,
    });
    t[0x63] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_63,
    });
    t[0x64] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_64,
    });
    t[0x65] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_65,
    });
    t[0x66] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_66,
    });
    t[0x67] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_67,
    });
    t[0x68] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_68,
    });
    t[0x69] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_69,
    });
    t[0x6a] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_6a,
    });
    t[0x6b] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_6b,
    });
    t[0x6c] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_6c,
    });
    t[0x6d] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_6d,
    });
    t[0x6e] = Some(LegacyInsn {
        size: 5,
        make: mk_ecma_6e,
    });
    t[0x6f] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_6f,
    });
    t[0x70] = Some(LegacyInsn {
        size: 10,
        make: mk_ecma_70,
    });
    t[0x71] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_71,
    });
    t[0x72] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_72,
    });
    t[0x73] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_73,
    });
    t[0x74] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_74,
    });
    t[0x75] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_75,
    });
    t[0x76] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_76,
    });
    t[0x77] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_77,
    });
    t[0x78] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_78,
    });
    t[0x79] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_79,
    });
    t[0x7a] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_7a,
    });
    t[0x7b] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_7b,
    });
    t[0x7c] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_7c,
    });
    t[0x7d] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_7d,
    });
    t[0x7e] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_7e,
    });
    t[0x7f] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_7f,
    });
    t[0x80] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_80,
    });
    t[0x81] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_81,
    });
    t[0x82] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_82,
    });
    t[0x83] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_83,
    });
    t[0x84] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_84,
    });
    t[0x87] = Some(LegacyInsn {
        size: 6,
        make: mk_ecma_87,
    });
    t[0x88] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_88,
    });
    t[0x89] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_89,
    });
    t[0x8a] = Some(LegacyInsn {
        size: 5,
        make: mk_ecma_8a,
    });
    t[0x8b] = Some(LegacyInsn {
        size: 7,
        make: mk_ecma_8b,
    });
    t[0x8c] = Some(LegacyInsn {
        size: 3,
        make: mk_ecma_8c,
    });
    t[0x8d] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_8d,
    });
    t[0x8e] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_8e,
    });
    t[0x8f] = Some(LegacyInsn {
        size: 4,
        make: mk_ecma_8f,
    });
    t[0x90] = Some(LegacyInsn {
        size: 2,
        make: mk_ecma_90,
    });
    t
};
