//! Low-level FFI bindings for the ArkCompiler bytecode ISA.
//!
//! This crate is generated at build time from the vendor ISA definition
//! (`isa.yaml`) and a C bridge layer. It exposes:
//!
//! - Raw C FFI functions (`isa_*`) via bindgen
//! - A safe [`Bytecode`] enum with per-instruction variants and operand accessors
//! - Per-mnemonic constructor types in the [`insn`] module
//! - Operand newtypes: [`Reg`], [`Imm`], [`EntityId`], [`Label`]
//! - Classification flags: [`BytecodeFlags`], [`ExceptionType`]
//!
//! Most users should depend on
//! [`abcd-isa`](https://crates.io/crates/abcd-isa) instead, which wraps
//! this crate in a safe `encode`/`decode` API.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    // The generated `bytecode.rs` names per-mnemonic constructors `new` by
    // ISA-spec convention (they return the `Bytecode` enum, not `Self`) and
    // emits explicit integer casts for width clarity. Both lints fire
    // hundreds of times on generated code; allow them crate-wide here rather
    // than distorting the generator template.
    clippy::new_ret_no_self,
    clippy::unnecessary_cast
)]

// Raw FFI bindings (generated by bindgen).
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Bytecode enum, operand newtypes, insn constructors (generated from bytecode.rs.erb).
include!(concat!(env!("OUT_DIR"), "/bytecode.rs"));

#[cfg(test)]
mod tests {
    //! Raw-FFI smoke tests for the isa bridge exports that the safe layer
    //! pre-validates away (the emitter's UNBOUND_LABELS error switch arm) or
    //! that no in-selection package drives (the pure-lookup classification
    //! and version families — those are exercised end-to-end by abcd-isa in
    //! the full workspace metric).
    use super::*;

    /// `isa_emitter_build` must report `ISA_BUILD_UNBOUND_LABELS` when a
    /// label was created and referenced but never bound. The safe
    /// `abcd_isa::encode` pre-validates every jump target
    /// (`EncodeError::LabelOutOfBounds`) and binds every created label, so
    /// this arm is only reachable through the raw FFI.
    #[test]
    fn emitter_build_reports_unbound_labels() {
        unsafe {
            let e = isa_emitter_create();
            assert!(!e.is_null());
            let label = isa_emitter_create_label(e);
            assert_ne!(label, u32::MAX);

            // Emit `jmp <label>` and deliberately never bind it.
            let bc = insn::Jmp::new(Label(0));
            let (opcode, mut args, num_args) = bc.emit_args();
            let label_idx = bc
                .jump_label_arg_index()
                .expect("jmp carries a label operand");
            args[label_idx] = i64::from(label);
            let rc = isa_emitter_emit(e, opcode, args.as_ptr(), num_args);
            assert_eq!(rc, ISA_EMIT_OK as i32, "emit must succeed");

            // Poison the out-params: build must overwrite them on failure.
            let mut buf = std::ptr::dangling_mut::<u8>();
            let mut len = 77usize;
            let rc = isa_emitter_build(e, &mut buf, &mut len);
            assert_eq!(
                rc, ISA_BUILD_UNBOUND_LABELS as i32,
                "an unbound label must report ISA_BUILD_UNBOUND_LABELS"
            );
            assert!(buf.is_null(), "failed build must null the buffer");
            assert_eq!(len, 0, "failed build must zero the length");
            isa_emitter_destroy(e);
        }
    }

    /// Positive control for the emitter path: a bound program builds and the
    /// buffer is released through `isa_emitter_free_buf`.
    #[test]
    fn emitter_build_bound_program_roundtrip() {
        unsafe {
            let e = isa_emitter_create();
            assert!(!e.is_null());
            let bc = insn::Returnundefined::new();
            let (opcode, args, num_args) = bc.emit_args();
            assert_eq!(
                isa_emitter_emit(e, opcode, args.as_ptr(), num_args),
                ISA_EMIT_OK as i32
            );
            let mut buf = std::ptr::null_mut::<u8>();
            let mut len = 0usize;
            assert_eq!(
                isa_emitter_build(e, &mut buf, &mut len),
                ISA_BUILD_OK as i32
            );
            assert!(!buf.is_null());
            assert!(len > 0);
            isa_emitter_free_buf(buf);
            isa_emitter_destroy(e);
        }
    }

    /// The pure-lookup classification family: exact flag answers for
    /// opcodes whose semantics are pinned by abcd-isa's bytecode tests.
    #[test]
    fn classification_exports_answer_for_known_opcodes() {
        unsafe {
            let jmp = insn::Jmp::new(Label(0)).emit_args().0;
            let ldundef = insn::Ldundefined::new().emit_args().0;
            let ret = insn::Return::new().emit_args().0;
            let retund = insn::Returnundefined::new().emit_args().0;
            let throw = insn::Throw::new().emit_args().0;
            let range = insn::Callthisrange::new(Imm(0), Imm(0), Reg(0))
                .emit_args()
                .0;
            let call0 = insn::Callarg0::new(Imm(0)).emit_args().0;
            let suspend = insn::Suspendgenerator::new(Reg(0)).emit_args().0;

            assert_eq!(isa_is_jump_opcode(jmp), 1);
            assert_eq!(isa_is_jump_opcode(ldundef), 0);
            assert_eq!(isa_can_throw_opcode(throw), 1);
            assert_eq!(isa_can_throw_opcode(ldundef), 0);
            assert_eq!(isa_is_terminator_opcode(retund), 1);
            assert_eq!(isa_is_terminator_opcode(ldundef), 0);
            assert_eq!(isa_is_range_opcode(range), 1);
            assert_eq!(isa_is_range_opcode(call0), 0);
            assert_eq!(isa_is_return_or_throw_opcode(ret), 1);
            assert_eq!(isa_is_return_or_throw_opcode(ldundef), 0);
            // The SUSPEND flag is never assigned by the ISA (pinned quirk):
            // even suspendgenerator reports 0.
            assert_eq!(isa_is_suspend_opcode(suspend), 0);
            assert_eq!(isa_is_suspend_opcode(ret), 0);
            assert_eq!(
                isa_is_throw_ex_opcode(throw, ExceptionType::X_THROW.bits()),
                1
            );
            assert_eq!(
                isa_is_throw_ex_opcode(throw, ExceptionType::X_NULL.bits()),
                0
            );
            // An out-of-range opcode is rejected by the validity guard.
            assert_eq!(isa_is_jump_opcode(u16::MAX), 0);
        }
    }

    /// The version-query family: current/min version, the API-level lookup
    /// (hit and miss), the compatibility predicate both ways, and the
    /// incompatible-version blocklist with its bounds guard.
    #[test]
    fn version_exports_answer_queries() {
        unsafe {
            let mut cur = [0u8; 4];
            isa_get_version(cur.as_mut_ptr());
            assert_ne!(cur, [0, 0, 0, 0], "current version must be set");
            let mut min = [0u8; 4];
            isa_get_min_version(min.as_mut_ptr());
            assert!(min <= cur, "min version must not exceed current");

            assert_eq!(isa_is_version_compatible(cur.as_ptr()), 1);
            assert_eq!(
                isa_is_version_compatible([0xFF, 0xFF, 0xFF, 0xFF].as_ptr()),
                0,
                "a version past current must be incompatible"
            );

            let mut out = [0u8; 4];
            assert_eq!(isa_get_version_by_api(12, out.as_mut_ptr()), 0);
            assert_ne!(out, [0, 0, 0, 0]);
            assert_eq!(
                isa_get_version_by_api(250, out.as_mut_ptr()),
                1,
                "an unknown API level must report failure"
            );

            assert_eq!(
                isa_get_version_by_api_sub(12, c"beta1".as_ptr(), out.as_mut_ptr()),
                0
            );
            // NB: no failing case here — GetVersionByApi falls back for
            // unknown API levels when a sub-API is given (version.rs docs),
            // so api_sub's error arm has no deterministic trigger.

            let count = isa_incompatible_version_count();
            // Out-of-range index: the guard returns without touching `out`.
            let mut probe = [0xAAu8; 4];
            isa_incompatible_version_at(count, probe.as_mut_ptr());
            assert_eq!(probe, [0xAA; 4]);
            // Every blocklist entry must round-trip through the predicate.
            for i in 0..count {
                let mut v = [0u8; 4];
                isa_incompatible_version_at(i, v.as_mut_ptr());
                assert_eq!(
                    isa_is_version_incompatible(v.as_ptr()),
                    1,
                    "blocklist entry {v:?} must report incompatible"
                );
            }
        }
    }
}
