//! Low-level FFI bindings for the ArkCompiler bytecode ISA.
//!
//! This crate is generated at build time from the vendor ISA definition
//! (`isa.yaml`) and a C bridge layer. It exposes:
//!
//! - Raw C FFI functions (`isa_*`) via bindgen
//! - A safe [`Bytecode`] enum with per-instruction variants and operand accessors
//! - Per-mnemonic constructor types in the [`insn`] module
//! - Operand newtypes: [`Reg`], [`Imm`], [`EntityId`], [`Label`]
//! - Classification flags: [`BytecodeFlag`], [`ExceptionType`]
//!
//! Most users should depend on
//! [`abcd-isa`](https://crates.io/crates/abcd-isa) instead, which wraps
//! this crate in a safe `encode`/`decode` API.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

// Raw FFI bindings (generated by bindgen).
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Bytecode enum, operand newtypes, insn constructors (generated from bytecode.rs.erb).
include!(concat!(env!("OUT_DIR"), "/bytecode.rs"));
