/**
 * C bridge for abcd-file-sys.
 *
 * Thin C wrapper over arkcompiler's libpandafile C++ data accessors.
 * Each C++ accessor maps to an opaque struct with open/close lifecycle.
 */

#ifndef FILE_BRIDGE_H
#define FILE_BRIDGE_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Constants (ACC_*, LiteralTag, ModuleTag, SourceLang, TypeId, FunctionKind)
 * are generated by bindgen from vendor C++ headers via file_bridge_enums.hpp.
 * See enum_bindings.rs in OUT_DIR. */

/* Common callback types.
 *
 * CALLBACK EARLY-STOP CONTRACT (audit finding #15):
 * `int`-returning callbacks imply an early-stop convention, but early stop
 * is honored ONLY where the function's doc explicitly says so — currently
 * the debug-info family (abc_debug_get_line_table / _get_column_table /
 * _get_local_vars / _get_parameter_info) and
 * abc_param_annotations_enumerate. Everywhere else the callback's return
 * value is DISCARDED and enumeration always runs to completion:
 *   - all 12 abc_{class,method,field}_enumerate_{,runtime_,type_}annotations
 *     sites (they wrap the vendored void-returning EnumerateAnnotations;
 *     upstream models early stop as SEPARATE functions,
 *     EnumerateAnnotationsWithEarlyStop, which this bridge does not use),
 *   - abc_code_enumerate_try_blocks_full (vendored void EnumerateTryBlocks).
 * The `int` return is kept for signature uniformity only. The Rust
 * wrappers always collect-all and never rely on early stop. */
typedef int (*AbcAnnotationCb)(uint32_t annotation_off, void *ctx);

/* ========== File handle ========== */

typedef struct AbcFileHandle AbcFileHandle;

AbcFileHandle *abc_file_open(const uint8_t *data, size_t len);
void abc_file_close(AbcFileHandle *f);
/* Reason for the last failed abc_file_open (thread-local; empty on success). */
const char *abc_file_open_error(void);

/* Header access */
uint32_t abc_file_num_classes(const AbcFileHandle *f);
uint32_t abc_file_class_offset(const AbcFileHandle *f, uint32_t idx);
uint32_t abc_file_num_literalarrays(const AbcFileHandle *f);
uint32_t abc_file_literalarray_offset(const AbcFileHandle *f, uint32_t idx);

uint32_t abc_file_size(const AbcFileHandle *f);

/* Version from header */
void abc_file_version(const AbcFileHandle *f, uint8_t out[4]);

/* String access: returns bytes written, 0 on error */
size_t abc_file_get_string(const AbcFileHandle *f, uint32_t offset,
                           char *buf, size_t buf_len);

/* String access via MUTF-8 → UTF-16 conversion (lossless for the whole
 * Unicode range, unlike the raw-byte view). Returns the number of UTF-16
 * units (excluding any terminator); SIZE_MAX on error. Zero is a valid
 * empty string. Query with buf=null.
 * buf must hold at least the returned unit count. */
size_t abc_file_get_string_utf16(const AbcFileHandle *f, uint32_t offset,
                                 uint16_t *buf, size_t buf_len);

uint32_t abc_resolve_class_index(const AbcFileHandle *f, uint32_t entity_off, uint16_t idx);

/* Class lookup by MUTF-8 name: returns offset, UINT32_MAX if not found */
uint32_t abc_file_get_class_id(const AbcFileHandle *f, const char *mutf8_name);
/* Check if entity is in the foreign section */
int abc_file_is_external(const AbcFileHandle *f, uint32_t entity_off);
/* Read the name offset of a foreign field/method item (stored as the u32
 * at item+4). Returns UINT32_MAX if out of bounds or not in the foreign
 * region. */
uint32_t abc_foreign_item_name_off(const AbcFileHandle *f, uint32_t entity_off);

/* Checksum validation: 1 = valid */
int abc_file_validate_checksum(const AbcFileHandle *f);

/* File type: -1 = invalid, 0 = dynamic, 1 = static */
int8_t abc_file_get_type(const uint8_t *data, int32_t size);

/* Index headers */
struct AbcIndexHeader {
    uint32_t start;
    uint32_t end;
    uint32_t class_idx_size;
    uint32_t class_idx_off;
    uint32_t method_idx_size;
    uint32_t method_idx_off;
    uint32_t field_idx_size;
    uint32_t field_idx_off;
    uint32_t proto_idx_size;
    uint32_t proto_idx_off;
};

/* Resolve by generic index: returns offset, UINT32_MAX on error */
uint32_t abc_resolve_offset_by_index(const AbcFileHandle *f, uint32_t entity_off, uint16_t idx);

/* Additional header fields */
uint32_t abc_file_checksum(const AbcFileHandle *f);
uint32_t abc_file_foreign_off(const AbcFileHandle *f);
uint32_t abc_file_foreign_size(const AbcFileHandle *f);

/* ========== Version Utilities ========== */

/* ========== Proto Data Accessor ========== */

typedef struct AbcProtoAccessor AbcProtoAccessor;

AbcProtoAccessor *abc_proto_open(const AbcFileHandle *f, uint32_t proto_off);
void abc_proto_close(AbcProtoAccessor *a);
uint32_t abc_proto_num_args(AbcProtoAccessor *a);
uint8_t abc_proto_get_return_type(const AbcProtoAccessor *a);
uint8_t abc_proto_get_arg_type(const AbcProtoAccessor *a, uint32_t idx);
uint32_t abc_proto_get_reference_type(AbcProtoAccessor *a, uint32_t idx);
uint32_t abc_proto_get_ref_num(AbcProtoAccessor *a);

typedef void (*AbcProtoTypeCb)(uint8_t type_id, void *ctx);
void abc_proto_enumerate_types(AbcProtoAccessor *a, AbcProtoTypeCb cb, void *ctx);

/* ========== Class Data Accessor ========== */

typedef struct AbcClassAccessor AbcClassAccessor;

AbcClassAccessor *abc_class_open(const AbcFileHandle *f, uint32_t offset);
void abc_class_close(AbcClassAccessor *a);
uint32_t abc_class_super_class_off(AbcClassAccessor *a);
uint32_t abc_class_access_flags(AbcClassAccessor *a);

/* Returns source file entity offset, UINT32_MAX if absent */
uint32_t abc_class_source_file_off(AbcClassAccessor *a);

/* Enumerate methods: callback receives method offset (no early-stop) */
typedef void (*AbcMethodOffsetCb)(uint32_t method_offset, void *ctx);
void abc_class_enumerate_methods(AbcClassAccessor *a, AbcMethodOffsetCb cb, void *ctx);

/* Enumerate fields: callback receives field offset (no early-stop) */
typedef void (*AbcFieldOffsetCb)(uint32_t field_offset, void *ctx);
void abc_class_enumerate_fields(AbcClassAccessor *a, AbcFieldOffsetCb cb, void *ctx);

/* Interfaces */
uint32_t abc_class_get_ifaces_number(AbcClassAccessor *a);
uint32_t abc_class_get_interface_id(AbcClassAccessor *a, uint32_t idx);

/* Source language: returns SourceLang value, UINT8_MAX if absent */
uint8_t abc_class_get_source_lang(AbcClassAccessor *a);

/* Class-level annotations. cb return value DISCARDED (no early stop — see
 * the contract block above); same for every *_enumerate_*annotations
 * function in this header. */
void abc_class_enumerate_annotations(AbcClassAccessor *a, AbcAnnotationCb cb, void *ctx);
void abc_class_enumerate_runtime_annotations(AbcClassAccessor *a, AbcAnnotationCb cb, void *ctx);

/* Class type annotations */
void abc_class_enumerate_type_annotations(AbcClassAccessor *a, AbcAnnotationCb cb, void *ctx);
void abc_class_enumerate_runtime_type_annotations(AbcClassAccessor *a, AbcAnnotationCb cb, void *ctx);

/* Class annotation counts and ID */

uint32_t abc_class_get_class_id(const AbcClassAccessor *a);

/* Class descriptor (raw MUTF-8 bytes, null-terminated) and name */
const uint8_t *abc_class_get_descriptor(const AbcClassAccessor *a);
size_t abc_class_get_name(const AbcClassAccessor *a, char *buf, size_t buf_len);

/* ========== Method Data Accessor ========== */

typedef struct AbcMethodAccessor AbcMethodAccessor;

AbcMethodAccessor *abc_method_open(const AbcFileHandle *f, uint32_t offset);
void abc_method_close(AbcMethodAccessor *a);

uint32_t abc_method_access_flags(AbcMethodAccessor *a);
/* Returns code offset, UINT32_MAX if absent */
uint32_t abc_method_code_off(AbcMethodAccessor *a);
/* Returns debug info offset, UINT32_MAX if absent */
uint32_t abc_method_debug_info_off(AbcMethodAccessor *a);

/* Resolved entity IDs (not raw indices) */

uint32_t abc_method_get_proto_id(const AbcMethodAccessor *a);

/* Source language: UINT8_MAX if absent */
uint8_t abc_method_get_source_lang(AbcMethodAccessor *a);

/* Method annotations */
void abc_method_enumerate_annotations(AbcMethodAccessor *a, AbcAnnotationCb cb, void *ctx);
void abc_method_enumerate_runtime_annotations(AbcMethodAccessor *a, AbcAnnotationCb cb, void *ctx);

/* Parameter annotation IDs: UINT32_MAX if absent */
uint32_t abc_method_get_param_annotation_id(AbcMethodAccessor *a);
uint32_t abc_method_get_runtime_param_annotation_id(AbcMethodAccessor *a);

/* Enumerate a ParamAnnotationsItem's entries: cb(param_idx, annotation_off).
 * A NONZERO cb return STOPS enumeration early (honored here). Returns 0 on
 * success, -1 on malformed/out-of-bounds data. */
typedef int (*AbcParamAnnotationCb)(uint32_t param_idx, uint32_t annotation_off, void *ctx);
int abc_param_annotations_enumerate(const AbcFileHandle *f, uint32_t item_off,
                                    AbcParamAnnotationCb cb, void *ctx);

/* Method type annotations */
void abc_method_enumerate_type_annotations(AbcMethodAccessor *a, AbcAnnotationCb cb, void *ctx);
void abc_method_enumerate_runtime_type_annotations(AbcMethodAccessor *a, AbcAnnotationCb cb, void *ctx);

/* Method annotation counts, size, ID, and misc */

uint32_t abc_method_get_method_id(const AbcMethodAccessor *a);
int abc_method_has_valid_proto(const AbcMethodAccessor *a);

/* Method name via MUTF-8 -> UTF-16 (lossless; query with buf=null) */
size_t abc_method_get_name_utf16(const AbcMethodAccessor *a, uint16_t *buf, size_t buf_len);

/* ========== Code Data Accessor ========== */

typedef struct AbcCodeAccessor AbcCodeAccessor;

AbcCodeAccessor *abc_code_open(const AbcFileHandle *f, uint32_t offset);
void abc_code_close(AbcCodeAccessor *a);
uint32_t abc_code_num_vregs(const AbcCodeAccessor *a);
uint32_t abc_code_num_args(const AbcCodeAccessor *a);
uint32_t abc_code_code_size(const AbcCodeAccessor *a);
const uint8_t *abc_code_instructions(const AbcCodeAccessor *a);

/* Enumerate try blocks with full catch block info.
 * cb return value DISCARDED (no early stop — see the contract block above). */
struct AbcTryBlockInfo {
    uint32_t start_pc;
    uint32_t length;
    uint32_t num_catches;
};
struct AbcCatchBlockInfo {
    uint32_t type_idx;
    uint32_t handler_pc;
    uint32_t code_size;
};
typedef int (*AbcTryBlockFullCb)(const struct AbcTryBlockInfo *try_info,
                                  const struct AbcCatchBlockInfo *catches, void *ctx);
void abc_code_enumerate_try_blocks_full(AbcCodeAccessor *a, AbcTryBlockFullCb cb, void *ctx);

/* ========== Field Data Accessor ========== */

typedef struct AbcFieldAccessor AbcFieldAccessor;

AbcFieldAccessor *abc_field_open(const AbcFileHandle *f, uint32_t offset);
void abc_field_close(AbcFieldAccessor *a);
uint32_t abc_field_name_off(const AbcFieldAccessor *a);
uint32_t abc_field_type(AbcFieldAccessor *a);
/* TypeId of the field's type, classified via Type::GetTypeFromFieldEncoding:
   primitives/tagged map to their TypeId, class offsets map to REFERENCE. */
uint8_t abc_field_type_id(AbcFieldAccessor *a);
uint32_t abc_field_access_flags(AbcFieldAccessor *a);

/* Enumerate field annotations */
void abc_field_enumerate_annotations(AbcFieldAccessor *a, AbcAnnotationCb cb, void *ctx);
void abc_field_enumerate_runtime_annotations(AbcFieldAccessor *a, AbcAnnotationCb cb, void *ctx);

/* Field initial values: returns 1 if present, 0 if absent */
int abc_field_get_value_i32(AbcFieldAccessor *a, int32_t *out);
int abc_field_get_value_i64(AbcFieldAccessor *a, int64_t *out);
int abc_field_get_value_f32(AbcFieldAccessor *a, float *out);
int abc_field_get_value_f64(AbcFieldAccessor *a, double *out);

/* Field type annotations */
void abc_field_enumerate_type_annotations(AbcFieldAccessor *a, AbcAnnotationCb cb, void *ctx);
void abc_field_enumerate_runtime_type_annotations(AbcFieldAccessor *a, AbcAnnotationCb cb, void *ctx);

/* Field annotation counts and ID */

uint32_t abc_field_get_field_id(const AbcFieldAccessor *a);

/* ========== Literal Data Accessor ========== */

typedef struct AbcLiteralAccessor AbcLiteralAccessor;

AbcLiteralAccessor *abc_literal_open(const AbcFileHandle *f, uint32_t literal_data_off);
void abc_literal_close(AbcLiteralAccessor *a);

/* Literal value union — tag determines which field is valid */
union AbcLiteralData {
    uint8_t  u8_val;
    uint16_t u16_val;
    uint32_t u32_val;
    uint64_t u64_val;
    float    f32_val;
    double   f64_val;
    uint8_t  bool_val;
};

struct AbcLiteralVal {
    uint8_t tag;       /* LiteralTag value */
    union AbcLiteralData data;
    /* String data — valid when tag is STRING or ARRAY_STRING.
     * str_data points into the file buffer; NULL for non-string tags. */
    const uint8_t *str_data;
    uint32_t str_utf16_len;
};

/* Enumerate literal values by index into the literal array table (no early-stop) */
typedef void (*AbcLiteralValCb)(const struct AbcLiteralVal *val, void *ctx);
void abc_literal_enumerate_vals(AbcLiteralAccessor *a, uint32_t array_off,
                                AbcLiteralValCb cb, void *ctx);

/* ========== Module Data Accessor ========== */

typedef struct AbcModuleAccessor AbcModuleAccessor;

AbcModuleAccessor *abc_module_open(const AbcFileHandle *f, uint32_t offset);
void abc_module_close(AbcModuleAccessor *a);

/* Number of request modules */
uint32_t abc_module_num_requests(const AbcModuleAccessor *a);
/* Get request module string offset by index */
uint32_t abc_module_request_off(const AbcModuleAccessor *a, uint32_t idx);

/* Module record callback: tag, export_name_off, module_request_idx, import_name_off, local_name_off (no early-stop) */
typedef void (*AbcModuleRecordCb)(uint8_t tag, uint32_t export_name_off,
                                  uint32_t module_request_idx,
                                  uint32_t import_name_off,
                                  uint32_t local_name_off, void *ctx);
void abc_module_enumerate_records(AbcModuleAccessor *a, AbcModuleRecordCb cb, void *ctx);

/* Module-request-phase blob (untagged u32 count + u8 lazy flags per module
 * request; vendored runtime layout in
 * ecmascript/module/module_data_extractor.cpp ModuleLazyImportFlagAccessor).
 * Returns the flag count, or -1 on error. The callback family here does not
 * early-stop (pure collector). */
int32_t abc_module_request_phase_read(const AbcFileHandle *f, uint32_t offset,
                                      void (*cb)(uint8_t flag, void *ctx), void *ctx);

/* ========== Annotation Data Accessor ========== */

typedef struct AbcAnnotationAccessor AbcAnnotationAccessor;

AbcAnnotationAccessor *abc_annotation_open(const AbcFileHandle *f, uint32_t offset);
void abc_annotation_close(AbcAnnotationAccessor *a);
uint32_t abc_annotation_class_off(const AbcAnnotationAccessor *a);
uint32_t abc_annotation_count(const AbcAnnotationAccessor *a);

/* Get element: returns name offset and raw value */
struct AbcAnnotationElem {
    uint32_t name_off;
    uint8_t  tag;      /* type tag char */
    uint32_t value;    /* raw scalar value or entity offset for arrays */
};
int abc_annotation_get_element(const AbcAnnotationAccessor *a, uint32_t idx,
                               struct AbcAnnotationElem *out);

/* Array element access: returns 0 on success, -1 on error */
struct AbcAnnotationArrayVal {
    uint32_t count;
    uint32_t entity_off;
};
int abc_annotation_get_array_element(const AbcAnnotationAccessor *a, uint32_t idx,
                                      struct AbcAnnotationArrayVal *out);

/* Typed scalar value access for >32-bit types (resolves entity offsets).
   Returns 0 on success, -1 on error. */
int abc_annotation_get_value_i64(const AbcAnnotationAccessor *a, uint32_t idx, int64_t *out);
int abc_annotation_get_value_u64(const AbcAnnotationAccessor *a, uint32_t idx, uint64_t *out);
int abc_annotation_get_value_f64(const AbcAnnotationAccessor *a, uint32_t idx, double *out);

/* Read annotation array elements.
   element_size: size in bytes of each element (1, 2, 4, or 8).
   out_values: output buffer for element values (zero-extended to uint64_t).
   max_count: capacity of out_values.
   Returns: number of elements read, or -1 on error. */
int abc_annotation_array_read(const AbcFileHandle *f, uint32_t entity_off,
                               uint32_t element_size, uint32_t count,
                               uint64_t *out_values, uint32_t max_count);

/* ========== MethodHandle ========== */

/* Read a MethodHandle item at the given file offset.
   Stores handle_type (0-8) in *out_type and the referenced entity offset in
   *out_entity_off.  Returns 0 on success, -1 if the offset is out of bounds. */
int abc_method_handle_read(const AbcFileHandle *f, uint32_t offset,
                           uint8_t *out_type, uint32_t *out_entity_off);

/* ========== Debug Info Extractor ========== */

typedef struct AbcDebugInfo AbcDebugInfo;

AbcDebugInfo *abc_debug_info_open(const AbcFileHandle *f);
void abc_debug_info_close(AbcDebugInfo *d);

/* Line number table for a method. A NONZERO cb return STOPS the callback
 * sequence early (the debug-info family honors early stop). */
struct AbcLineEntry {
    uint32_t offset;
    uint32_t line;
};
typedef int (*AbcLineEntryCb)(const struct AbcLineEntry *entry, void *ctx);
void abc_debug_get_line_table(const AbcDebugInfo *d, uint32_t method_off,
                              AbcLineEntryCb cb, void *ctx);

/* Column number table for a method */
struct AbcColumnEntry {
    uint32_t offset;
    uint32_t column;
};
typedef int (*AbcColumnEntryCb)(const struct AbcColumnEntry *entry, void *ctx);
void abc_debug_get_column_table(const AbcDebugInfo *d, uint32_t method_off,
                                AbcColumnEntryCb cb, void *ctx);

/* Local variable table for a method */
struct AbcLocalVarInfo {
    const char *name;
    const char *type;
    const char *type_signature;
    int32_t reg_number;
    uint32_t start_offset;
    uint32_t end_offset;
};
typedef int (*AbcLocalVarCb)(const struct AbcLocalVarInfo *info, void *ctx);
void abc_debug_get_local_vars(const AbcDebugInfo *d, uint32_t method_off,
                              AbcLocalVarCb cb, void *ctx);

/* Source file / source code for a method (returns nullptr if absent) */
const char *abc_debug_get_source_file(const AbcDebugInfo *d, uint32_t method_off);
const char *abc_debug_get_source_code(const AbcDebugInfo *d, uint32_t method_off);

/* Parameter info for a method */
struct AbcParamInfo {
    const char *name;
    const char *signature;
};
typedef int (*AbcParamInfoCb)(const struct AbcParamInfo *info, void *ctx);
void abc_debug_get_parameter_info(const AbcDebugInfo *d, uint32_t method_off,
                                   AbcParamInfoCb cb, void *ctx);

/* ========== Index Accessor ========== */

typedef struct AbcIndexAccessor AbcIndexAccessor;

AbcIndexAccessor *abc_index_open(const AbcFileHandle *f, uint32_t method_off);
void abc_index_close(AbcIndexAccessor *a);

/* FunctionKind encoded in access flags */
uint8_t abc_index_get_function_kind(const AbcIndexAccessor *a);

/* ========== ABC Builder (ItemContainer + MemoryWriter) ========== */

typedef struct AbcBuilder AbcBuilder;

AbcBuilder *abc_builder_new(void);
void abc_builder_free(AbcBuilder *b);

/* Set API policy before creating items (default: upstream current API). */
void abc_builder_set_api(AbcBuilder *b, uint8_t api, const char *sub_api);
/* Select an exact file version through the upstream API/version map.
 * Returns 1 on success; 0 leaves the builder policy unchanged. */
int abc_builder_set_file_version(AbcBuilder *b, const uint8_t version[4]);

/* Create / get items */
uint32_t abc_builder_add_string(AbcBuilder *b, const char *str);
uint32_t abc_builder_add_class(AbcBuilder *b, const char *descriptor);
uint32_t abc_builder_add_foreign_class(AbcBuilder *b, const char *descriptor);
/* Convenience: add the global class ("L_GLOBAL;") */
uint32_t abc_builder_add_global_class(AbcBuilder *b);
uint32_t abc_builder_add_literal_array(AbcBuilder *b, const char *id);

/* Add field to a class */
uint32_t abc_builder_class_add_field(AbcBuilder *b, uint32_t class_handle,
                                      const char *name, uint8_t type_id,
                                      uint32_t access_flags);
/* Extended: add field with reference type support */
uint32_t abc_builder_class_add_field_ex(AbcBuilder *b, uint32_t class_handle,
                                         const char *name, uint8_t type_id,
                                         uint32_t ref_class_handle, uint32_t access_flags);

/* Add typed items to a literal array (call once per item, in order) */
void abc_builder_literal_array_add_u8(AbcBuilder *b, uint32_t lit_handle, uint8_t val);
void abc_builder_literal_array_add_u16(AbcBuilder *b, uint32_t lit_handle, uint16_t val);
void abc_builder_literal_array_add_u32(AbcBuilder *b, uint32_t lit_handle, uint32_t val);
void abc_builder_literal_array_add_u64(AbcBuilder *b, uint32_t lit_handle, uint64_t val);
void abc_builder_literal_array_add_bool(AbcBuilder *b, uint32_t lit_handle, uint8_t val);

/* String literal: string_handle is an index returned by abc_builder_add_string */
void abc_builder_literal_array_add_string(AbcBuilder *b, uint32_t lit_handle, uint32_t string_handle);
/* Method literal: method_handle is an index returned by abc_builder_class_add_method_with_proto */
void abc_builder_literal_array_add_method(AbcBuilder *b, uint32_t lit_handle, uint32_t method_handle);
/* Literal array reference: ref_handle is an index returned by abc_builder_add_literal_array */
void abc_builder_literal_array_add_literalarray(AbcBuilder *b, uint32_t lit_handle, uint32_t ref_handle);

/* --- Module-record blob write support (ModuleDataAccessor layout) --- */

/* One module record entry. String handles are indices returned by
 * abc_builder_add_string; UINT32_MAX marks an absent name. `tag` is a
 * panda::panda_file::ModuleTag value (bindgen: ModuleTag_*). */
typedef struct AbcModuleRecordDef {
    uint8_t tag;
    uint32_t export_name_handle;
    uint32_t module_request_idx;
    uint32_t import_name_handle;
    uint32_t local_name_handle;
} AbcModuleRecordDef;

/* Stage a complete module-record blob into a literal array created by
 * abc_builder_add_literal_array. The blob follows the vendored UNTAGGED
 * ModuleDataAccessor layout (module_data_accessor.cpp ctor +
 * module_data_accessor-inl.h EnumerateModuleRecord): request count,
 * request string references, then per-tag section counts and entries in
 * vendored section order (regular/namespace/local/indirect/star). The
 * LiteralArrayItem itself writes the u32 item-count header. Nothing is
 * staged unless every input validates.
 * Returns 0 on success, -1 on error (bad handle, unknown tag, missing
 * required name, module_request_idx wider than the vendored u16 slot). */
/* Stage a module-request-phase blob (untagged u8 flags; see
 * abc_module_request_phase_read). Returns 0 on success, -1 on error. */
int32_t abc_builder_literal_array_add_module_request_phase(AbcBuilder *b, uint32_t lit_handle,
                                                           const uint8_t *flags, uint32_t num_flags);

int32_t abc_builder_literal_array_add_module_data(AbcBuilder *b, uint32_t lit_handle,
                                                  const uint32_t *request_handles,
                                                  uint32_t num_requests,
                                                  const AbcModuleRecordDef *records,
                                                  uint32_t num_records);

/* Finalize: compute layout, write to memory buffer.
 * Returns pointer to buffer (owned by builder), sets *out_len.
 * Returns NULL on error. Buffer valid until builder is freed. */
const uint8_t *abc_builder_finalize(AbcBuilder *b, uint32_t *out_len);

/* --- Proto --- */
/* Proto parameter descriptor for reference type support */
struct AbcProtoParam {
    uint8_t type_id;          /* ABC_TYPE_* constant */
    uint32_t class_handle;    /* tagged class handle when type_id == ABC_TYPE_REFERENCE, else ignored */
};
uint32_t abc_builder_create_proto(AbcBuilder *b, uint8_t ret_type_id,
                                   const uint8_t *param_type_ids, uint32_t num_params);
/* Extended proto creation with reference type support */
uint32_t abc_builder_create_proto_ex(AbcBuilder *b, uint8_t ret_type_id, uint32_t ret_class_handle,
                                      const struct AbcProtoParam *params, uint32_t num_params);
uint32_t abc_builder_class_add_method_with_proto(AbcBuilder *b, uint32_t class_handle,
    const char *name, uint32_t proto_handle, uint32_t access_flags,
    const uint8_t *code, uint32_t code_size, uint32_t num_vregs, uint32_t num_args);

/* --- Class configuration --- */
void abc_builder_class_set_access_flags(AbcBuilder *b, uint32_t class_handle, uint32_t flags);
void abc_builder_class_set_source_lang(AbcBuilder *b, uint32_t class_handle, uint8_t lang);
/* super_handle / iface_handle: high bit 0x80000000 = foreign class, else regular class */
void abc_builder_class_set_super_class(AbcBuilder *b, uint32_t class_handle, uint32_t super_handle);
void abc_builder_class_add_interface(AbcBuilder *b, uint32_t class_handle, uint32_t iface_handle);
void abc_builder_class_set_source_file(AbcBuilder *b, uint32_t class_handle, uint32_t string_handle);

/* --- Method configuration --- */
void abc_builder_method_set_source_lang(AbcBuilder *b, uint32_t method_handle, uint8_t lang);
void abc_builder_method_set_function_kind(AbcBuilder *b, uint32_t method_handle, uint8_t kind);
void abc_builder_method_set_debug_info(AbcBuilder *b, uint32_t method_handle, uint32_t debug_handle);

/* Bridge handle categories (not ABC on-disk values). */
enum AbcCodeEntityKind {
    ABC_CODE_STRING, ABC_CODE_METHOD, ABC_CODE_LITERAL_ARRAY,
    ABC_CODE_CLASS, ABC_CODE_FIELD
};
/* Register a target and defer patching until upstream assigns its index.
 * byte_offset is the start of an instruction; operand counts only ID fields.
 * Returns 1 on success, 0 for an invalid handle/code location. */
int abc_builder_relocate_code_id(AbcBuilder *b, uint32_t method_handle,
    uint32_t byte_offset, uint32_t operand, enum AbcCodeEntityKind kind, uint32_t target_handle);
/* The caller supplies the ISA updater so file-sys does not duplicate ISA
 * encoding rules. Return 1 on success, 0 on invalid operands/overflow. */
typedef int (*AbcCodeIdUpdater)(uint8_t *code, size_t code_size,
    uint32_t byte_offset, uint32_t operand, uint32_t new_id);
const uint8_t *abc_builder_finalize_with_code_ids(AbcBuilder *b, uint32_t *out_len,
    AbcCodeIdUpdater updater);

/* --- Field initial values --- */
void abc_builder_field_set_value_i32(AbcBuilder *b, uint32_t field_handle, int32_t value);
void abc_builder_field_set_value_i64(AbcBuilder *b, uint32_t field_handle, int64_t value);
void abc_builder_field_set_value_f32(AbcBuilder *b, uint32_t field_handle, float value);
void abc_builder_field_set_value_f64(AbcBuilder *b, uint32_t field_handle, double value);
/* Set a field's initial value to a literal-array item reference. The value
 * item is the vendored ScalarValueItem Type::ID, so the writer stores the
 * item's LAYOUT offset inline (FieldTag::VALUE + u32) — this is how es2abc
 * stores _ESModuleRecord/_ESScopeNamesRecord field values, and it relocates
 * automatically with the target item.
 * Returns 0 on success, -1 on an invalid field or literal-array handle. */
int32_t abc_builder_field_set_value_literalarray(AbcBuilder *b, uint32_t field_handle,
                                                 uint32_t lit_handle);

/* --- Try-Catch blocks --- */
struct AbcCatchBlockDef {
    uint32_t type_class_handle;  /* UINT32_MAX = catch-all, else tagged class handle */
    uint32_t handler_pc;
    uint32_t code_size;
};
uint32_t abc_builder_create_code(AbcBuilder *b, uint32_t num_vregs, uint32_t num_args,
                                  const uint8_t *instructions, uint32_t code_size);
void abc_builder_code_add_try_block(AbcBuilder *b, uint32_t code_handle,
    uint32_t start_pc, uint32_t length,
    const struct AbcCatchBlockDef *catches, uint32_t num_catches);
void abc_builder_method_set_code(AbcBuilder *b, uint32_t method_handle, uint32_t code_handle);

/* --- Debug Info --- */
uint32_t abc_builder_create_lnp(AbcBuilder *b);
void abc_builder_lnp_emit_end(AbcBuilder *b, uint32_t lnp_handle);
void abc_builder_lnp_emit_advance_pc(AbcBuilder *b, uint32_t lnp_handle,
                                      uint32_t debug_handle, uint32_t value);
void abc_builder_lnp_emit_advance_line(AbcBuilder *b, uint32_t lnp_handle,
                                        uint32_t debug_handle, int32_t value);
void abc_builder_lnp_emit_column(AbcBuilder *b, uint32_t lnp_handle,
                                  uint32_t debug_handle, uint32_t pc_inc, uint32_t column);
void abc_builder_lnp_emit_start_local(AbcBuilder *b, uint32_t lnp_handle,
    uint32_t debug_handle, int32_t reg, uint32_t name_handle, uint32_t type_handle);
void abc_builder_lnp_emit_start_local_extended(AbcBuilder *b, uint32_t lnp_handle,
    uint32_t debug_handle, int32_t reg,
    uint32_t name_handle, uint32_t type_handle, uint32_t type_sig_handle);
void abc_builder_lnp_emit_end_local(AbcBuilder *b, uint32_t lnp_handle, int32_t reg);
void abc_builder_lnp_emit_set_file(AbcBuilder *b, uint32_t lnp_handle,
                                    uint32_t debug_handle, uint32_t source_file_handle);
void abc_builder_lnp_emit_set_source_code(AbcBuilder *b, uint32_t lnp_handle,
                                           uint32_t debug_handle, uint32_t source_code_handle);
uint32_t abc_builder_create_debug_info(AbcBuilder *b, uint32_t lnp_handle, uint32_t line_number);
void abc_builder_debug_add_param(AbcBuilder *b, uint32_t debug_handle, uint32_t name_string_handle);

/* --- Annotations --- */
struct AbcAnnotationElemDef {
    uint32_t name_string_handle;
    char     tag;       /* AnnotationDataAccessor::Tag character */
    uint32_t value;     /* scalar value or entity handle */
};
uint32_t abc_builder_create_annotation(AbcBuilder *b, uint32_t class_handle,
    const struct AbcAnnotationElemDef *elements, uint32_t num_elements);

/* Extended annotation element definition supporting array and 64-bit values */
struct AbcAnnotationElemDefEx {
    uint32_t name_string_handle;
    char     tag;
    uint8_t  is_array;            /* 0=scalar32, 1=array, 2=scalar64, 3=entity_ref, 4=entity_array */
    uint32_t scalar_value;        /* used when is_array == 0 */
    uint64_t scalar_value_64;     /* used when is_array == 2 */
    const uint32_t *array_values; /* used when is_array == 1 */
    uint32_t array_count;         /* used when is_array == 1 */
};
uint32_t abc_builder_create_annotation_ex(AbcBuilder *b, uint32_t class_handle,
    const struct AbcAnnotationElemDefEx *elements, uint32_t num_elements);
void abc_builder_class_add_annotation(AbcBuilder *b, uint32_t class_handle, uint32_t ann_handle);
void abc_builder_class_add_runtime_annotation(AbcBuilder *b, uint32_t class_handle, uint32_t ann_handle);
void abc_builder_class_add_type_annotation(AbcBuilder *b, uint32_t class_handle, uint32_t ann_handle);
void abc_builder_class_add_runtime_type_annotation(AbcBuilder *b, uint32_t class_handle, uint32_t ann_handle);
void abc_builder_method_add_annotation(AbcBuilder *b, uint32_t method_handle, uint32_t ann_handle);
void abc_builder_method_add_runtime_annotation(AbcBuilder *b, uint32_t method_handle, uint32_t ann_handle);
void abc_builder_method_add_type_annotation(AbcBuilder *b, uint32_t method_handle, uint32_t ann_handle);
void abc_builder_method_add_runtime_type_annotation(AbcBuilder *b, uint32_t method_handle, uint32_t ann_handle);

/* --- Method parameter annotations --- */

/* Add a typed parameter to a method. Call after method creation, before adding param annotations.
   Returns param index (0-based), or UINT32_MAX on error.
   type_id: ABC_TYPE_* constant */
uint32_t abc_builder_method_add_param(AbcBuilder *b, uint32_t method_handle, uint8_t type_id);

/* Add a typed parameter with reference type support.
 * class_handle: tagged class handle when type_id == ABC_TYPE_REFERENCE, else ignored.
 * Returns param index (0-based), or UINT32_MAX on error. */
uint32_t abc_builder_method_add_param_ex(AbcBuilder *b, uint32_t method_handle,
    uint8_t type_id, uint32_t class_handle);

/* Add annotation to a specific method parameter */
void abc_builder_method_param_add_annotation(AbcBuilder *b, uint32_t method_handle,
    uint32_t param_idx, uint32_t ann_handle);
void abc_builder_method_param_add_runtime_annotation(AbcBuilder *b, uint32_t method_handle,
    uint32_t param_idx, uint32_t ann_handle);
void abc_builder_method_param_add_type_annotation(AbcBuilder *b, uint32_t method_handle,
    uint32_t param_idx, uint32_t ann_handle);
void abc_builder_method_param_add_runtime_type_annotation(AbcBuilder *b, uint32_t method_handle,
    uint32_t param_idx, uint32_t ann_handle);

/* Seal staged param annotations into a ParamAnnotationsItem and link it
 * into the method's tagged data. is_runtime: 0 = compile-time
 * (MethodTag::PARAM_ANNOTATION), 1 = runtime (RUNTIME_PARAM_ANNOTATION).
 * Call after method_add_param + method_param_add_* for that bucket.
 * Returns 1 on success, 0 on invalid handle. */
int abc_builder_method_seal_param_annotations(AbcBuilder *b, uint32_t method_handle, int is_runtime);

void abc_builder_field_add_annotation(AbcBuilder *b, uint32_t field_handle, uint32_t ann_handle);
void abc_builder_field_add_runtime_annotation(AbcBuilder *b, uint32_t field_handle, uint32_t ann_handle);
void abc_builder_field_add_type_annotation(AbcBuilder *b, uint32_t field_handle, uint32_t ann_handle);
void abc_builder_field_add_runtime_type_annotation(AbcBuilder *b, uint32_t field_handle, uint32_t ann_handle);

/* --- Foreign items --- */
uint32_t abc_builder_add_foreign_field(AbcBuilder *b, uint32_t class_handle,
                                        const char *name, uint8_t type_id);
uint32_t abc_builder_add_foreign_method(AbcBuilder *b, uint32_t class_handle,
                                         const char *name, uint32_t proto_handle, uint32_t access_flags);

/* --- MethodHandle items --- */
/* type: 0-3 = field ops, 4-8 = method ops.
   entity_handle: field or method handle (high bit = foreign). */
uint32_t abc_builder_create_method_handle(AbcBuilder *b, uint8_t type, uint32_t entity_handle);

/* --- Deduplication --- */
void abc_builder_deduplicate(AbcBuilder *b);
void abc_builder_deduplicate_code_and_debug_info(AbcBuilder *b);
void abc_builder_deduplicate_annotations(AbcBuilder *b);

/* ---------- Test helpers ---------- */

#ifdef __cplusplus
}
#endif

#endif /* FILE_BRIDGE_H */
